import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── Chapter 36 — Constructing the Borel and Lebesgue measure ──────────────
  premeasure: {
    term: 'Pre-measure',
    definition:
      'A function μ₀ on an algebra 𝒜₀ satisfying μ₀(∅) = 0 and countable additivity whenever the union of a disjoint sequence in 𝒜₀ also lies in 𝒜₀. Weaker than a measure because the algebra may not be closed under countable unions.',
    example: 'The area function on finite unions of rectangles in ℝ² is a pre-measure on the algebra generated by rectangles.',
  },
  algebraOfSets: {
    term: 'Algebra of sets',
    definition:
      'A nonempty collection 𝒜₀ of subsets of Ω that is closed under complement and finite union. Like a σ-algebra but with "countable" weakened to "finite" everywhere.',
    example: 'Finite unions of intervals and their complements in ℝ form an algebra — but not a σ-algebra, since a countable union of intervals need not be in the family.',
  },
  outerMeasure: {
    term: 'Outer measure',
    symbol: '\\mu^\\ast',
    definition:
      'A function μ* : 2^Ω → [0,∞] satisfying μ*(∅) = 0, monotonicity (E ⊆ F ⟹ μ*(E) ≤ μ*(F)), and countable sub-additivity μ*(⋃ Eₙ) ≤ ∑ μ*(Eₙ). Defined on all subsets of Ω, but only sub-additive, not additive.',
    example: 'The Lebesgue outer measure λ*(A) = inf{∑ lengths of open intervals covering A} is an outer measure on ℝ.',
  },
  sigmaAlgebra: {
    term: 'σ-algebra',
    symbol: '\\mathcal{A}',
    definition:
      'A nonempty collection 𝒜 of subsets of Ω closed under complement and countably infinite union (and hence countably infinite intersection). The domain on which a measure is defined.',
    example: 'The Borel σ-algebra ℬ(ℝ) is the smallest σ-algebra on ℝ containing all open intervals.',
  },
  caratheodoryMeasurable: {
    term: 'Carathéodory measurable set',
    definition:
      'A set A ⊆ Ω is Carathéodory measurable with respect to an outer measure μ* if for every E ⊆ Ω: μ*(E) = μ*(E ∩ A) + μ*(E \\ A). The collection of all such sets forms a σ-algebra on which μ* restricts to a complete measure.',
    example: 'Every open subset of ℝⁿ is Carathéodory measurable with respect to the Lebesgue outer measure.',
  },
  completeMeasureSpace: {
    term: 'Complete measure space',
    definition:
      'A measure space (Ω, 𝒜, μ) is complete if every subset of a null set (a set of measure zero) also belongs to 𝒜 and has measure zero. Completeness ensures that "negligible dust" is always measurable.',
    example: 'The Lebesgue measure space (ℝ, ℒ(ℝ), λ) is complete; the Borel measure space (ℝ, ℬ(ℝ), μ) is not.',
  },
  lebesgueOuterMeasure: {
    term: 'Lebesgue outer measure',
    symbol: '\\lambda^\\ast',
    definition:
      'The outer measure λ*(A) = inf{∑ μ₀(Aₙ) : Aₙ ∈ ℒ₀, A ⊆ ⋃ Aₙ}, obtained from the rectangle pre-measure λ₀ by the Carathéodory construction. It assigns every subset of ℝⁿ a size in [0,∞], and agrees with the usual volume on rectangles.',
  },
  lebesgueMeasure: {
    term: 'Lebesgue measure',
    symbol: '\\lambda',
    definition:
      'The restriction of the Lebesgue outer measure λ* to the σ-algebra ℒ(ℝⁿ) of Carathéodory-measurable sets. It is the unique complete extension of the rectangle pre-measure λ₀ to a full measure on ℝⁿ.',
    example: 'λ([0,1]ⁿ) = 1; λ(ℚ) = 0 (the rationals have Lebesgue measure zero in ℝ).',
  },
  lebesgueSigmaAlgebra: {
    term: 'Lebesgue σ-algebra',
    symbol: '\\mathcal{L}(\\mathbb{R}^n)',
    definition:
      'The σ-algebra of Carathéodory-measurable sets with respect to the Lebesgue outer measure λ* on ℝⁿ. It strictly contains the Borel σ-algebra ℬ(ℝⁿ): every Borel set is Lebesgue measurable, but not every Lebesgue measurable set is Borel.',
  },
  borelSigmaAlgebra: {
    term: 'Borel σ-algebra',
    symbol: '\\mathcal{B}(\\mathbb{R}^n)',
    definition:
      'The smallest σ-algebra on ℝⁿ containing all open sets. Equivalently, the σ-algebra generated by the rectangle algebra ℒ₀. Every continuous function is Borel measurable.',
    example: 'Open sets, closed sets, Gδ sets, and Fσ sets are all Borel. The Cantor set is Borel (it is a closed set).',
  },
  nullSet: {
    term: 'Null set',
    definition:
      'A measurable set A with μ(A) = 0. In a complete measure space, every subset of a null set is also a null set. The rationals ℚ ⊆ ℝ form a null set under the Lebesgue measure.',
    example: 'The Cantor set is uncountable but has Lebesgue measure zero — it is a null set.',
  },
  completionMeasure: {
    term: 'Completion of a measure space',
    symbol: '(\\Omega,\\overline{\\mathcal{A}},\\overline{\\mu})',
    definition:
      'Given a measure space (Ω, 𝒜, μ), its completion is (Ω, 𝒜̄, μ̄) where 𝒜̄ = {A ∪ N : A ∈ 𝒜, N ⊆ null set} and μ̄(A ∪ N) = μ(A). It is the smallest complete measure space extending (Ω, 𝒜, μ).',
    example: 'The Lebesgue measure space is the completion of the Borel measure space on ℝⁿ.',
  },
  sigmaFinite: {
    term: 'σ-finite measure',
    definition:
      'A measure μ on Ω is σ-finite if Ω = ⋃ₙ Aₙ for countably many sets Aₙ with μ(Aₙ) < ∞. σ-finiteness is needed for the uniqueness half of the Carathéodory extension theorem.',
    example: 'The Lebesgue measure on ℝ is σ-finite: ℝ = ⋃ₙ [−n, n] and λ([−n, n]) = 2n < ∞.',
  },
  cantorSet: {
    term: 'Cantor set',
    symbol: 'C',
    definition:
      'The "middle-thirds Cantor set" C ⊆ [0,1] built by repeatedly removing the open middle third of each remaining interval. It is closed, uncountable (its elements are ternary expansions omitting the digit 1), yet has Lebesgue measure zero.',
    example: 'After n steps, the remaining set has measure (2/3)ⁿ, which → 0, so λ(C) = 0.',
  },
};

export default entries;
