import type { GlossaryEntry } from '@/lib/glossary';

// ────────────── Chapter 42 — Stopped martingales ──────────────

const glossaryChapter: Record<string, GlossaryEntry> = {
  // §1 — How to make money almost surely
  probabilitySpace: {
    term: 'Probability space',
    symbol: '(\\Omega, \\mathcal{A}, \\mu)',
    definition: 'A measure space (Ω, 𝒜, μ) where μ(Ω) = 1. The set Ω is the sample space (all possible outcomes), 𝒜 is a σ-algebra of measurable events, and μ is a probability measure assigning each event a likelihood in [0, 1].',
    example: 'Flipping a fair coin: Ω = {H, T}, 𝒜 = all subsets, μ(H) = μ(T) = 1/2.',
  },

  // §2 — Sub-σ-algebras and filtrations
  subSigmaAlgebra: {
    term: 'Sub-σ-algebra',
    symbol: '\\mathcal{F} \\subseteq \\mathcal{A}',
    definition: 'A σ-algebra ℱ on a probability space (Ω, 𝒜, μ) that is contained in 𝒜: every measurable set in ℱ is also measurable in 𝒜. It captures a restricted collection of observable events — the information you currently have access to.',
    example: 'If you only know whether the first coin flip was heads or tails, your sub-σ-algebra contains just ∅, {first flip H}, {first flip T}, and Ω.',
  },
  sigmaGeneratedBy: {
    term: 'σ-algebra generated by a random variable',
    symbol: '\\sigma(X)',
    definition: 'For a random variable X: Ω → ℝ, the σ-algebra σ(X) = {X⁻¹(B) | B ⊆ ℝ measurable} is the smallest sub-σ-algebra making X measurable. It captures exactly the information that X reveals about ω.',
    example: 'If X is the result of one die roll, σ(X) contains the events {X = 1}, {X = 2}, …, {X = 6} and all their unions.',
  },
  filtration: {
    term: 'Filtration',
    symbol: '\\mathcal{F}_0 \\subseteq \\mathcal{F}_1 \\subseteq \\cdots',
    definition: 'A nested increasing sequence of sub-σ-algebras ℱ₀ ⊆ ℱ₁ ⊆ ℱ₂ ⊆ … on a probability space. Each ℱₙ represents the information available at time n — as time advances, we learn more.',
    example: 'Flipping coins one at a time: ℱₙ is generated by the first n flips. ℱ₀ = {∅, Ω} (no information); ℱ₁ knows the first flip; ℱ₂ knows the first two; and so on.',
  },
  adaptedProcess: {
    term: 'Adapted process',
    symbol: 'X_n \\text{ is } \\mathcal{F}_n\\text{-measurable}',
    definition: 'A sequence of random variables (Xₙ) is adapted to a filtration (ℱₙ) if each Xₙ is measurable with respect to ℱₙ. Informally: the value of Xₙ is determined by the information available at time n — you can observe it without needing future knowledge.',
    example: 'Your casino bankroll at time n is determined by the outcomes of flips 1 through n, so it is adapted to the natural coin-flip filtration.',
  },

  // §3 — Conditional expectation
  conditionalExpectation: {
    term: 'Conditional expectation',
    symbol: '\\mathbb{E}(X \\mid \\mathcal{F})',
    definition: 'For an integrable random variable X and a sub-σ-algebra ℱ, the conditional expectation 𝔼(X | ℱ) is the unique (up to a.e.) ℱ-measurable function η such that 𝔼[η · 1_A] = 𝔼[X · 1_A] for every A ∈ ℱ. It is the best ℱ-measurable approximation to X.',
    example: 'If X and Y are uniform on [0,1] and ℱ = σ(X+Y), then 𝔼(X | X+Y) = (X+Y)/2 as a function of ω.',
  },

  // §4 — Supermartingales
  supermartingale: {
    term: 'Supermartingale',
    symbol: '\\mathbb{E}(X_n \\mid \\mathcal{F}_{n-1}) \\le X_{n-1}',
    definition: 'A sequence of integrable adapted random variables (Xₙ) such that 𝔼(Xₙ | ℱₙ₋₁) ≤ Xₙ₋₁ almost everywhere for all n. In expectation, the process can only decrease — like wealth in a game with house edge.',
    example: 'Your bankroll at a casino with a house edge is a supermartingale: each bet lowers your expected wealth.',
  },
  submartingale: {
    term: 'Submartingale',
    symbol: '\\mathbb{E}(X_n \\mid \\mathcal{F}_{n-1}) \\ge X_{n-1}',
    definition: 'A sequence of integrable adapted random variables (Xₙ) such that 𝔼(Xₙ | ℱₙ₋₁) ≥ Xₙ₋₁ almost everywhere. In expectation, the process can only increase — the reverse of a supermartingale.',
    example: 'If (Xₙ) is a supermartingale, then (−Xₙ) is a submartingale.',
  },
  martingale: {
    term: 'Martingale',
    symbol: '\\mathbb{E}(X_n \\mid \\mathcal{F}_{n-1}) = X_{n-1}',
    definition: 'A sequence of integrable adapted random variables (Xₙ) such that 𝔼(Xₙ | ℱₙ₋₁) = Xₙ₋₁ almost everywhere. It models a fair game: the expected future value equals the present value, regardless of history.',
    example: 'A symmetric random walk (step +1 or −1 each with probability 1/2) is a martingale.',
  },
  doobConvergence: {
    term: "Doob's martingale convergence theorem",
    symbol: 'X_n \\xrightarrow{\\mathrm{a.s.}} X_\\infty',
    definition: 'If (Xₙ) is a supermartingale with supₙ 𝔼[|Xₙ|] < ∞, then Xₙ converges almost surely to a finite limit X_∞. A bounded martingale or supermartingale cannot oscillate forever.',
    example: 'A martingale bounded between −1 and 1 converges almost surely to some random variable X_∞.',
  },

  // §5 — Optional stopping
  stoppingTime: {
    term: 'Stopping time',
    symbol: '\\tau \\colon \\Omega \\to \\{0,1,2,\\dots\\} \\cup \\{\\infty\\}',
    definition: 'A function τ: Ω → {0,1,…,∞} adapted to a filtration in the sense that {ω : τ(ω) = n} ∈ ℱₙ for every n. The decision to stop at time n can only use information available at time n — no peeking at the future.',
    example: 'The first time a random walk hits 5 is a stopping time. "The time one step before the walk hits 5" is not — that requires future knowledge.',
  },
  stoppedMartingale: {
    term: 'Stopped martingale',
    symbol: 'X_{\\tau \\wedge n}',
    definition: 'Given a martingale (Xₙ) and stopping time τ, the stopped process is X_{τ∧n}(ω) = X_{min(τ(ω), n)}(ω). It freezes at the stopping time: if τ(ω) = 3 then X_{τ∧4}(ω) = X_{τ∧5}(ω) = … = X₃(ω).',
    example: 'If τ is the first time a random walk exits [−5, 5], then X_{τ∧n} traces the walk until it exits, then stays constant at the exit value.',
  },
  optionalStopping: {
    term: 'Optional stopping theorem',
    symbol: '\\mathbb{E}[X_\\tau] \\le \\mathbb{E}[X_0]',
    definition: "Doob's optional stopping theorem: if (Xₙ) is a supermartingale and τ is a stopping time satisfying one of the sane conditions (finite time, bounded values, or finite expected stopping time with bounded increments), then 𝔼[Xτ] ≤ 𝔼[X₀]. For a martingale, equality holds.",
    example: 'In a fair casino, no matter when you decide to leave, your expected final wealth equals your starting wealth.',
  },
};

export default glossaryChapter;
