import type { GlossaryEntry } from '../glossary';

// Glossary entries for Chapter 62 — Bonus: A Bit on Artin Reciprocity
// (part-15-algebraic-nt-ii-galois-and-ramification-theory/05-bonus-a-bit-on-artin-reciprocity).
//
// Keys are prefixed `gr62` (part 15, chapter 62) to guarantee uniqueness
// against sibling chapters 01–04 of the same part, which are authored in
// parallel and may independently define terms like "ramified" or
// "Frobenius". Some foundational number-theory keys (number fields, rings
// of integers, ideal/class groups, prime ideals, signature) are reused
// from the already-merged Part XIV glossary-chapters files instead of
// being redefined here.

const entries: Record<string, GlossaryEntry> = {
  gr62AbelianExt: {
    term: 'Abelian extension',
    symbol: 'L/K',
    definition: 'A field extension L/K such that the Galois group Gal(L/K) is an abelian group. Class field theory is the study of abelian extensions of a number field K.',
    example: 'ℚ(√2)/ℚ is abelian (Galois group ℤ/2ℤ). ℚ(∛2)/ℚ is not even Galois, let alone abelian.',
  },
  gr62ArtinSymbol: {
    term: 'Artin symbol',
    symbol: '\\left(\\tfrac{L/K}{\\mathfrak p}\\right)',
    definition: 'For an abelian extension L/K and a prime 𝔭 of K unramified in L, the Artin symbol is the Frobenius element Frob_𝔓 ∈ Gal(L/K) (which does not depend on the choice of prime 𝔓 of L above 𝔭, since Gal(L/K) is abelian). It generalizes the Legendre symbol.',
    example: 'For L = ℚ(√2), K = ℚ, the Artin symbol at an odd prime p sends √2 ↦ (2/p)·√2, recovering the Legendre symbol (2/p).',
  },
  gr62LegendreSymbol: {
    term: 'Legendre symbol',
    symbol: '\\left(\\tfrac ap\\right)',
    definition: 'For a prime p and integer a not divisible by p, the Legendre symbol (a/p) is +1 if a is a quadratic residue mod p, and −1 otherwise. Computed as a^((p−1)/2) mod p.',
    example: '(2/7) = 1 since 3² ≡ 2 (mod 7). (3/7) = −1 since no x has x² ≡ 3 (mod 7).',
  },
  gr62Modulus: {
    term: 'Modulus (module)',
    symbol: '\\mathfrak m = \\prod_\\mathfrak{p} \\mathfrak p^{\\nu(\\mathfrak p)}',
    definition: 'A formal product 𝔪 over all primes 𝔭 of K, finite and infinite, of nonnegative integers ν(𝔭), only finitely many nonzero. Complex infinite primes must have exponent 0, and real infinite primes exponent at most 1. Splits as 𝔪 = 𝔪₀𝔪∞ (finite part times infinite part).',
    example: '𝔪 = 8∞ in ℚ means: exponent 3 at the finite prime 2, exponent 1 at the infinite prime ∞, exponent 0 everywhere else.',
  },
  gr62RayClassGroup: {
    term: 'Ray class group',
    symbol: 'C_K(\\mathfrak m)',
    definition: 'For a modulus 𝔪 of K, the ray class group is C_K(𝔪) = I_K(𝔪)/P_K(𝔪): the fractional ideals coprime to 𝔪, modulo those generated by elements ≡ 1 mod 𝔪. It is always finite, and generalizes the ordinary ideal class group (the case 𝔪 = 1).',
    example: 'C_ℚ(8) ≅ (ℤ/4ℤ)ˣ. C_ℚ(8∞) ≅ (ℤ/8ℤ)ˣ, the extra infinite prime removes the ± ambiguity in ideal generators.',
  },
  gr62InfinitePrime: {
    term: 'Infinite prime',
    symbol: '\\sigma \\colon K \\to \\CC',
    definition: 'A real infinite prime of K is a real embedding σ: K → ℝ. A complex infinite prime is a conjugate pair {σ, σ̄} of complex embeddings K → ℂ. Together with the usual (finite) prime ideals, these make up "all the primes" of K in class field theory.',
    example: 'ℚ has one real infinite prime, usually written ∞. ℚ(√-5) has one complex infinite prime.',
  },
  gr62TotallyReal: {
    term: 'Totally real field',
    definition: 'A number field K all of whose infinite primes are real, i.e. every embedding K → ℂ actually lands in ℝ.',
    example: 'ℚ(√5) is totally real: both its embeddings are real.',
  },
  gr62TotallyComplex: {
    term: 'Totally complex field',
    definition: 'A number field K all of whose infinite primes are complex, i.e. K has no real embeddings at all.',
    example: 'ℚ(√-5) is totally complex: its two embeddings form one conjugate pair, no real embeddings.',
  },
  gr62CongruenceMod: {
    term: 'Congruence modulo an infinite prime',
    symbol: 'a \\equiv b \\pmod{\\mathfrak p}',
    definition: 'For a real infinite prime 𝔭 = σ, we declare a ≡ b (mod 𝔭) whenever σ(a/b) > 0 — i.e. a and b have the same sign under the embedding σ. Congruence modulo a full modulus 𝔪 means congruence modulo every prime power factor of 𝔪 simultaneously.',
  },
  gr62IK: {
    term: 'Ideals coprime to a modulus',
    symbol: 'I_K(\\mathfrak m)',
    definition: 'The group of all fractional ideals of K that are relatively prime to the finite part of the modulus 𝔪 (infinite primes impose no ideal-level condition, only element-level ones). An abelian group under ideal multiplication.',
  },
  gr62PK: {
    term: 'Ray of principal ideals',
    symbol: 'P_K(\\mathfrak m)',
    definition: 'The subgroup of I_K(𝔪) generated by principal ideals αO_K where α ∈ K× and α ≡ 1 (mod 𝔪). Called a "ray" because, like a geometric ray, it only extends in one direction once an infinite prime sits in 𝔪.',
  },
  gr62CongruenceSubgroup: {
    term: 'Congruence subgroup',
    symbol: 'H',
    definition: 'For a modulus 𝔪, a subgroup H of I_K(𝔪) satisfying P_K(𝔪) ⊆ H ⊆ I_K(𝔪). Every congruence subgroup determines a quotient I_K(𝔪)/H sitting between the ray class group C_K(𝔪) and the trivial group.',
  },
  gr62RamifiedInfinite: {
    term: 'Ramified infinite prime',
    definition: 'A real infinite prime σ of K ramifies in a Galois extension L/K if at least one embedding τ of L extending σ is complex. Complex infinite primes never ramify — only a real prime can "turn complex" when lifted.',
    example: 'The real infinite prime ∞ of ℚ ramifies in ℚ(√-5)/ℚ (the extension is totally complex), but is unramified in ℚ(√5)/ℚ (the extension is totally real).',
  },
  gr62GaloisGroup: {
    term: 'Galois group Gal(L/K)',
    symbol: '\\Gal(L/K)',
    definition: 'For a Galois extension L/K, the group of field automorphisms of L that fix K pointwise, under composition. Its order equals [L:K]. L/K is abelian if this group is abelian.',
    example: 'Gal(ℚ(i)/ℚ) ≅ ℤ/2ℤ, generated by complex conjugation.',
  },
  gr62FrobElement: {
    term: 'Frobenius element',
    symbol: '\\Frob_{\\mathfrak P}',
    definition: 'For an unramified prime 𝔭 of K and a prime 𝔓 of L above it (L/K Galois), the unique element Frob_𝔓 ∈ Gal(L/K) that acts on O_L/𝔓 as α ↦ α^(N(𝔭)) — the residue-field Frobenius, lifted to the Galois group.',
    example: 'For L = ℚ(i), K = ℚ and p ≡ 3 (mod 4), Frob_𝔓 is complex conjugation.',
  },
  gr62InertialDegree: {
    term: 'Inertial degree f(𝔓|𝔭)',
    symbol: 'f(\\mathfrak P \\mid \\mathfrak p)',
    definition: 'The degree of the residue field extension [O_L/𝔓 : O_K/𝔭]. Equals the order of the Frobenius element Frob_𝔓 when 𝔭 is unramified. 𝔭 splits completely in L/K exactly when f = 1 for every prime above it.',
    example: 'In ℚ(i)/ℚ, an odd prime p ≡ 1 (mod 4) splits completely (f=1); p ≡ 3 (mod 4) stays inert with f=2.',
  },
  gr62CubicResidueSymbol: {
    term: 'Cubic residue symbol',
    symbol: '\\left(\\tfrac{a}{\\theta}\\right)_3',
    definition: 'For a primary prime θ in ℤ[ω] (the Eisenstein integers) and a ∈ ℤ[ω] not divisible by θ, the cubic residue symbol (a/θ)₃ is the cube root of unity ω^k with a^((N(θ)−1)/3) ≡ ω^k (mod θ). It is +1 exactly when a is a cube mod θ.',
  },
  gr62RamSet: {
    term: 'Ramification set Ram(L/K)',
    symbol: '\\Ram(L/K)',
    definition: 'The set of primes of K (finite or infinite) that ramify in a Galois extension L/K. A modulus 𝔪 usable for the Artin map must be divisible by every prime in Ram(L/K).',
  },
  gr62ArtinMap: {
    term: 'Artin map',
    symbol: '\\left(\\tfrac{L/K}{\\bullet}\\right) \\colon I_K(\\mathfrak m) \\surjto \\Gal(L/K)',
    definition: 'The multiplicative extension of the Artin symbol to a surjective homomorphism I_K(𝔪) ↠ Gal(L/K), defined whenever 𝔪 is divisible by all ramified primes of L/K. Surjectivity follows from the Chebotarev density theorem.',
  },
  gr62HLK: {
    term: 'Artin-map kernel H(L/K,m)',
    symbol: 'H(L/K, \\mathfrak m)',
    definition: 'The kernel of the Artin map I_K(𝔪) ↠ Gal(L/K), so that Gal(L/K) ≅ I_K(𝔪)/H(L/K,𝔪). It is always a congruence subgroup once 𝔪 is divisible by the conductor of L/K.',
  },
  gr62Conductor: {
    term: 'Conductor 𝔣(L/K)',
    symbol: '\\kf(L/K)',
    definition: 'For an abelian extension L/K, the smallest modulus 𝔣 (divisible by exactly the ramified primes) such that P_K(𝔪) ⊆ H(L/K,𝔪) for every 𝔪 divisible by 𝔣. Plays a role for L/K analogous to the discriminant.',
    example: 'The conductor of ℚ(ζ_m)/ℚ divides m∞, and equality is the generic case.',
  },
  gr62HilbertClassField: {
    term: 'Hilbert class field',
    symbol: 'E',
    definition: 'For a number field K, the unique maximal abelian extension E/K that is unramified at every prime, finite or infinite. Its Galois group Gal(E/K) is canonically isomorphic to the ideal class group Cl_K, via the Artin symbol. A prime 𝔭 of K splits completely in E if and only if 𝔭 is principal.',
    example: 'ℚ(√-5, i) is the Hilbert class field of ℚ(√-5), whose class group has order 2.',
  },
  gr62SplitCompletely: {
    term: 'Splits completely',
    definition: 'A prime 𝔭 of K splits completely in an extension L if it factors into [L:K] distinct prime ideals of L, each with inertial degree 1 (and ramification index 1). Equivalently, the Frobenius/Artin symbol at 𝔭 is the identity.',
    example: 'A prime p ≡ 1 (mod 4) splits completely in ℚ(i): (p) = 𝔓₁𝔓₂ with both factors of norm p.',
  },
};

export default entries;
