import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  fan67Category: {
    term: 'Category (generic name)',
    symbol: '\\mathcal{A}, \\mathcal{B}',
    definition:
      'Script letters like 𝒜, 𝓑 stand for an arbitrary category — a collection of objects together with arrows between them that compose associatively and have identities.',
    example: '𝒜 might be Grp, Vect_k, Top, Set, or any other category; the letter is just a placeholder.',
  },
  fan67Functor: {
    term: 'Functor',
    symbol: 'F \\colon \\mathcal{A} \\to \\mathcal{B}',
    definition:
      'A functor F from 𝒜 to 𝓑 sends every object A of 𝒜 to an object F(A) of 𝓑, and every arrow A₁ → A₂ to an arrow F(A₁) → F(A₂), in a way that preserves identities (F(id_A) = id_{F(A)}) and composition (F(g∘f) = F(g)∘F(f)).',
    example: 'Sending each group to its underlying set, and each homomorphism to itself viewed as a set map, is a functor Grp → Set.',
  },
  fan67Forgetful: {
    term: 'Forgetful functor',
    symbol: 'U \\colon \\mathcal{A} \\to \\mathrm{Set}',
    definition:
      'An informal name for a functor that takes an object with extra structure (a group, ring, vector space, …) and returns its underlying set, forgetting the structure. Arrows are sent to the same map, just viewed as a plain function.',
    example: 'The forgetful functor Vect_k → Set sends a vector space to its underlying set and a linear map to its underlying function.',
  },
  fan67Free: {
    term: 'Free functor',
    symbol: 'F \\colon \\mathrm{Set} \\to \\mathcal{A}',
    definition:
      'An informal name for a functor going the other way from forgetful: it builds the "most general" structured object generated by a plain set, with no relations beyond what the structure demands.',
    example: 'The free functor Set → Vect_k sends a set S to the vector space with basis S, and a function f : S → T to the linear map sending each basis vector s to the basis vector f(s).',
  },
  fan67Faithful: {
    term: 'Faithful functor',
    symbol: 'F \\colon \\mathcal{A} \\to \\mathcal{B} \\text{ faithful}',
    definition:
      'A functor F is faithful if for every pair of objects A₁, A₂, the map F : Hom(A₁,A₂) → Hom(FA₁,FA₂) is injective — distinct arrows never get merged together.',
    example: 'Every forgetful functor to Set is faithful: two different homomorphisms never become the same underlying function.',
  },
  fan67Full: {
    term: 'Full functor',
    symbol: 'F \\colon \\mathcal{A} \\to \\mathcal{B} \\text{ full}',
    definition:
      'A functor F is full if for every pair of objects A₁, A₂, the map F : Hom(A₁,A₂) → Hom(FA₁,FA₂) is surjective — every arrow between the images comes from some arrow upstairs.',
    example: 'The forgetful functor Grp → Set is faithful but not full: not every set map between underlying sets comes from a group homomorphism.',
  },
  fan67ConcreteCategory: {
    term: 'Concrete category',
    symbol: 'U \\colon \\mathcal{A} \\to \\mathrm{Set} \\text{ faithful}',
    definition:
      'A category equipped with a faithful forgetful functor to Set. This makes precise the idea that objects "are" sets with extra structure, and arrows "are" structure-preserving functions.',
    example: 'Grp, Vect_k, Top, and CRing are all concrete categories via their usual forgetful functors to Set.',
  },
  fan67HomSet: {
    term: 'Hom-set',
    symbol: '\\Hom_{\\mathcal{A}}(A_1, A_2)',
    definition:
      'The set of all arrows from A₁ to A₂ in a category 𝒜. Fixing the first slot and letting the second vary (or vice versa) turns Hom into a functor.',
    example: 'In Grp, Hom_Grp(ℤ, G) is the set of homomorphisms ℤ → G, which is in bijection with the underlying set of G.',
  },
  fan67CovariantYoneda: {
    term: 'Covariant Yoneda functor',
    symbol: 'H^A(A_1) \\defeq \\Hom_{\\mathcal{A}}(A, A_1)',
    definition:
      'For a fixed object A, the functor H^A : 𝒜 → Set sends A₁ to the set of arrows from A to A₁, and sends an arrow f : A₁ → A₂ to the map "post-compose with f". Informally, H^A records how A sees the rest of the category.',
    example: 'For A = ℤ in Grp, H^ℤ(G) = Hom(ℤ,G) is in bijection with the underlying set of G — arrows out of ℤ recover elements.',
  },
  fan67ContravariantYoneda: {
    term: 'Contravariant Yoneda functor',
    symbol: 'H_A(X) \\defeq \\Hom_{\\mathcal{A}}(X, A)',
    definition:
      'For a fixed object A, the functor H_A : 𝒜ᵒᵖ → Set sends X to the set of arrows from X to A, and sends an arrow f : X → Y to the map "pre-compose with f", which goes from Hom(Y,A) to Hom(X,A). Informally, H_A records how the rest of the category sees A.',
    example: 'For A = k (the base field) in Vect_k, H_k(V) = Hom(V,k) is exactly the dual space V∨.',
  },
  fan67OppositeCategory: {
    term: 'Opposite category',
    symbol: '\\mathcal{A}\\op',
    definition:
      'The category 𝒜ᵒᵖ has the same objects as 𝒜, but every arrow is reversed: an arrow A₁ → A₂ in 𝒜ᵒᵖ is really an arrow A₂ → A₁ in 𝒜. It lets us describe "backwards" constructions as ordinary (covariant) functors out of 𝒜ᵒᵖ.',
    example: 'The dual-space operation V ↦ V∨ is a covariant functor Vect_k\\op → Vect_k, even though it reverses the direction of every linear map.',
  },
  fan67OneObjectCategory: {
    term: 'One-object category from a group',
    symbol: '\\mathcal{G} = \\{\\ast\\}',
    definition:
      'Given a group G, build a category 𝒢 with a single object ∗, whose arrows ∗ → ∗ are exactly the elements of G (composition is the group operation, identity is 1_G). Any group can be viewed this way, turning group theory into a special case of category theory with one object.',
    example: 'For G = ℤ/3ℤ, the category 𝒢 has one object and three arrows ∗ → ∗, composing like addition mod 3.',
  },
  fan67Cat: {
    term: 'The category of categories',
    symbol: '\\Cat',
    definition:
      'The category whose objects are (small) categories and whose arrows are functors between them. Composition of functors and the identity functor make Cat itself a category — categories and functors slot into the same framework they were built to describe.',
  },
  fan67CategoryTwo: {
    term: 'The discrete two-object category 2',
    symbol: '\\mathbf{2}',
    definition:
      'The category with exactly two objects, 0 and 1, and no arrows besides the two identities id₀, id₁. A functor 2 → 𝒜 amounts to just picking an ordered pair of objects of 𝒜, with no compatibility conditions to check.',
    example: 'A functor F : 2 → Grp with F(0) = ℤ, F(1) = ℤ/2ℤ is fully determined by that choice alone — there are no non-identity arrows to worry about.',
  },
  fan67ProductCategory: {
    term: 'Product category',
    symbol: '\\mathcal{A} \\times \\mathcal{A}',
    definition:
      'The category whose objects are pairs (A₁, A₂) of objects of 𝒜, and whose arrows (A₁,A₂) → (A₁\', A₂\') are pairs of arrows A₁ → A₁\' and A₂ → A₂\', composed coordinatewise.',
    example: 'In Top × Top, an arrow (X₁,Y₁) → (X₂,Y₂) is a pair of continuous maps (f,g) with f : X₁ → X₂ and g : Y₁ → Y₂.',
  },
  fan67Presheaf: {
    term: 'Presheaf',
    symbol: 'X \\colon \\mathcal{A}\\op \\to \\Set',
    definition:
      'A presheaf on 𝒜 is just a contravariant functor 𝒜ᵒᵖ → Set (or into some other target category). The name comes from topology: a presheaf on the open sets of a space X assigns data to each open set, contravariantly in restriction maps.',
    example: 'A contravariant functor Opens(X)ᵒᵖ → Rings is "a family of rings indexed by the open sets of X, with restriction maps between them" — the presheaf of continuous real-valued functions is a standard example.',
  },
  fan67FullyFaithful: {
    term: 'Fully faithful functor',
    symbol: 'F \\colon \\mathcal{A} \\to \\mathcal{B} \\text{ fully faithful}',
    definition:
      'A functor that is both full and faithful: for every A₁, A₂, the map Hom(A₁,A₂) → Hom(FA₁,FA₂) is a bijection. It embeds 𝒜 into 𝓑 so that arrows match up exactly, though objects of 𝓑 outside the image of F are allowed.',
    example: 'The functor A ↦ H^A embedding 𝒜 into its functor category is fully faithful — this is the "Yoneda embedding," discussed in §7.',
  },
  fan67EssentiallySurjective: {
    term: 'Essentially surjective functor',
    symbol: 'F \\colon \\mathcal{A} \\to \\mathcal{B} \\text{ essentially surjective}',
    definition:
      'A functor F : 𝒜 → 𝓑 is essentially surjective if every object of 𝓑 is isomorphic to F(A) for some A ∈ 𝒜 — not necessarily equal, just isomorphic. "Essentially" signals that we only need to hit every isomorphism class.',
    example: 'The inclusion of finite-dimensional vector spaces of the specific form kⁿ into all finite-dimensional vector spaces is essentially surjective: every finite-dimensional space is isomorphic to some kⁿ.',
  },
  fan67EquivalenceOfCategories: {
    term: 'Equivalence of categories',
    symbol: '\\mathcal{A} \\simeq \\mathcal{B}',
    definition:
      'A functor F : 𝒜 → 𝓑 is an equivalence of categories if there is a functor G : 𝓑 → 𝒜 and natural isomorphisms G∘F ≅ id_𝒜 and F∘G ≅ id_𝓑 (equality only up to natural isomorphism, unlike an isomorphism of categories). Equivalently — and this is the practical test — F is an equivalence exactly when it is fully faithful and essentially surjective.',
    example: 'The category of finite-dimensional vector spaces over k is equivalent to the category with one object kⁿ for each n ≥ 0 and Hom(kⁿ,kᵐ) = m×n matrices — a much smaller category capturing exactly the same structure.',
  },
  fan67NaturalTransformation: {
    term: 'Natural transformation',
    symbol: '\\alpha \\colon F \\Rightarrow G',
    definition:
      'Given two functors F, G : 𝒜 → 𝓑, a natural transformation α assigns to every object A ∈ 𝒜 an arrow α_A : F(A) → G(A) (its component at A), subject to naturality: for every arrow A₁ → A₂ in 𝒜, going across then down agrees with going down then across in the resulting square built from F(A₁), F(A₂), G(A₁), G(A₂).',
    example: 'The determinant gives a natural transformation from GL_n (as a functor CRing → Grp) to the units functor R ↦ R^× — det(AB) = det(A)det(B) is exactly the naturality square for ring maps.',
  },
  fan67CategoryTwoPoset: {
    term: 'The poset category 2 (with 0 ≤ 1)',
    symbol: '\\mathbf{2}',
    definition:
      'The category generated by the two-element poset 0 ≤ 1: objects 0 and 1, identities id₀ and id₁, and one further nontrivial arrow 0 → 1. This is a different category from the discrete two-object category used in §3 to index pairs — this one has a genuine non-identity arrow between its objects.',
    example: 'A functor α : 𝒜 × 𝟐 → 𝓑 restricting to F on 𝒜 × {0} and G on 𝒜 × {1} is exactly a natural transformation F ⇒ G — the arrow 0 → 1 supplies the components α_A.',
  },
  fan67NaturalIsomorphism: {
    term: 'Natural isomorphism',
    symbol: 'F \\cong G',
    definition:
      'A natural transformation α : F ⇒ G whose every component α_A is an isomorphism. In this case there is an inverse natural transformation β : G ⇒ F, and we say F(A) ≅ G(A) naturally in A, or simply F ≅ G.',
    example: 'The map ε_V : V → (V∨)∨ sending v to "evaluate at v" is a natural isomorphism id ≅ (•∨)∨ on finite-dimensional vector spaces — the double-dual isomorphism that needs no choice of basis.',
  },
  fan67FunctorCategory: {
    term: 'Functor category',
    symbol: '[\\mathcal{A}, \\mathcal{B}]',
    definition:
      'The functor category [𝒜,𝓑] has as objects the (covariant) functors F : 𝒜 → 𝓑, and as arrows the natural transformations α : F ⇒ G between them. Composition is composition of natural transformations, and the identity arrow on F is the natural transformation with every component id_{F(A)}.',
    example: '[𝒜, Set] is the category of presheaves-in-disguise when 𝒜 is replaced by 𝒜ᵒᵖ — its objects are exactly the covariant functors 𝒜 → Set.',
  },
  fan67Representable: {
    term: 'Representable functor',
    symbol: 'X \\cong H_A',
    definition:
      'A presheaf X : 𝒜ᵒᵖ → Set is representable if X ≅ H_A for some object A ∈ 𝒜 — that is, X is naturally isomorphic to the contravariant Yoneda functor of some specific object. Asking "which presheaves are representable?" is asking which functors are already "built in" to 𝒜 itself.',
    example: 'The forgetful functor U : Grp → Set (viewed suitably) is representable by ℤ: Hom_Grp(ℤ,G) ≅ U(G) naturally, via φ ↦ φ(1).',
  },
  fan67YonedaLemma: {
    term: 'Yoneda lemma',
    symbol: '\\operatorname{Nat}(H_A, X) \\cong X(A)',
    definition:
      'For a category 𝒜, an object A ∈ 𝒜, and a contravariant functor X : 𝒜ᵒᵖ → Set, the map sending a natural transformation α : H_A ⇒ X to the single element α_A(id_A) ∈ X(A) is a bijection. In words: natural transformations out of the "arrows into A" functor are completely determined (and freely realized) by where the identity arrow on A goes.',
    example: 'Taking X = H_B recovers: natural transformations H_A ⇒ H_B correspond bijectively to arrows B → A — a special case worth checking by hand.',
  },
};

export default entries;
