/**
 * Chapter glossary for Part 14 Chapter 3 — Unique factorization (finally!).
 * All keys are prefixed with "an55" to guarantee portal-wide uniqueness.
 */
import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── §1 Motivation ──────────────
  an55ZSqrtMinus5: {
    term: 'ℤ[√-5]',
    symbol: '\\ZZ[\\sqrt{-5}]',
    definition: 'The ring of algebraic integers of the form a + b√-5, where a, b ∈ ℤ. The ring of integers of ℚ(√-5). It is the canonical example of a ring where unique element factorization fails: 6 = 2·3 = (1+√-5)(1-√-5).',
    example: '2, 3, 1+√-5, and 1-√-5 are all irreducible in ℤ[√-5], yet 6 = 2·3 = (1+√-5)(1-√-5).',
  },
  an55gcdIdeal: {
    term: 'GCD via ideals',
    definition: 'In a ring R the ideal (a₁, …, aₘ) = {r₁a₁ + ··· + rₘaₘ : rᵢ ∈ R} serves as a "generalized GCD" of a₁, …, aₘ. If the ideal happens to be principal, its generator is the classical GCD. When the ideal is not principal, no single-element GCD exists in R.',
    example: 'In ℤ, (35, 77) = (7) because gcd(35,77) = 7. In ℤ[√-5], (3, 1+√-5) is not principal.',
  },
  an55primeIdealOK: {
    term: 'Prime ideal in a ring of integers',
    symbol: '\\mathfrak{p} \\subseteq \\mathcal{O}_K',
    definition: 'A nonzero proper ideal 𝔭 of a ring of integers 𝒪_K such that whenever xy ∈ 𝔭, either x ∈ 𝔭 or y ∈ 𝔭. In a Dedekind domain, every nonzero prime ideal is also maximal.',
    example: 'In ℤ[√-5], the ideal (2, 1-√-5) is a prime ideal.',
  },
  an55ringOfIntegers: {
    term: 'Ring of integers 𝒪_K',
    symbol: '\\mathcal{O}_K',
    definition: 'For a number field K, the ring of integers 𝒪_K consists of all elements of K that are roots of a monic polynomial with integer coefficients. It generalises ℤ inside ℚ.',
    example: '𝒪_ℚ = ℤ. 𝒪_{ℚ(√-5)} = ℤ[√-5]. 𝒪_{ℚ(√5)} = ℤ[(1+√5)/2].',
  },

  // ────────────── §2 Ideal arithmetic ──────────────
  an55idealSum: {
    term: 'Sum of ideals 𝔞 + 𝔟',
    symbol: '\\mathfrak{a} + \\mathfrak{b}',
    definition: 'For ideals 𝔞 and 𝔟 in a ring R, their sum is {a + b : a ∈ 𝔞, b ∈ 𝔟}. It is an ideal; if 𝔞 = (a₁,…,aₙ) and 𝔟 = (b₁,…,bₘ) then 𝔞+𝔟 = (a₁,…,aₙ,b₁,…,bₘ). Ideal addition is the algebraic analogue of taking GCDs.',
    example: 'In ℤ, (4) + (6) = (4,6) = (2) because gcd(4,6) = 2.',
  },
  an55idealProduct: {
    term: 'Product of ideals 𝔞·𝔟',
    symbol: '\\mathfrak{a} \\cdot \\mathfrak{b}',
    definition: 'For ideals 𝔞 and 𝔟 in a ring R, their product is the ideal generated by all products ab with a ∈ 𝔞, b ∈ 𝔟: the set of all finite sums a₁b₁ + ··· + aₙbₙ. If 𝔞 = (a₁,…,aₙ) and 𝔟 = (b₁,…,bₘ) then 𝔞·𝔟 is generated by the aᵢbⱼ.',
    example: 'In ℤ, (3)·(5) = (15). In ℤ[√-5], (3,1+√-5)·(3,1-√-5) = (3).',
  },
  an55idealDivides: {
    term: 'Ideal divisibility 𝔞 ∣ 𝔟',
    symbol: '\\mathfrak{a} \\mid \\mathfrak{b}',
    definition: 'An ideal 𝔞 divides an ideal 𝔟 (written 𝔞 ∣ 𝔟) if 𝔞 ⊇ 𝔟. Note the reversal: larger ideals are smaller divisors. This mirrors how (3) ⊇ (15) because every multiple of 15 is a multiple of 3.',
    example: 'In ℤ, (3) ∣ (15) because (15) ⊆ (3). In ℤ[√-5], (3,1-√-5) divides both (3) and (1-√-5).',
  },

  // ────────────── §3 Dedekind domains ──────────────
  an55dedekindDomain: {
    term: 'Dedekind domain',
    symbol: '\\mathcal{A}',
    definition: 'An integral domain that is Noetherian, integrally closed, and in which every nonzero prime ideal is maximal. The key condition is that prime ideals = maximal ideals. Every ring of integers 𝒪_K is a Dedekind domain.',
    example: 'ℤ is a Dedekind domain. ℤ[√-5] is a Dedekind domain. The coordinate ring of a smooth affine curve is a Dedekind domain.',
  },
  an55integrallyClosed: {
    term: 'Integrally closed',
    definition: 'An integral domain R with field of fractions K is integrally closed if the only elements of K that are roots of monic polynomials with coefficients in R are elements of R itself. Informally: R contains all algebraic integers in its fraction field.',
    example: 'ℤ is integrally closed in ℚ: by the rational root theorem, any rational root of a monic integer polynomial is an integer. ℤ[2√2] is not integrally closed because √2 satisfies x²-2 but √2 ∉ ℤ[2√2].',
  },
  an55numberField: {
    term: 'Number field',
    symbol: 'K',
    definition: 'A finite extension of ℚ — a field K ⊇ ℚ with [K : ℚ] finite. Number fields are the natural setting for algebraic number theory. Their rings of integers 𝒪_K are Dedekind domains.',
    example: 'ℚ(√-5), ℚ(i), ℚ(∛2), and ℚ(ζ_p) for a p-th root of unity ζ_p are number fields.',
  },

  // ────────────── §4 Unique factorization works ──────────────
  an55idealFactorization: {
    term: 'Unique ideal factorization',
    definition: 'In a Dedekind domain, every nonzero proper ideal factors uniquely as a product of prime ideals: 𝔞 = 𝔭₁^e₁ ··· 𝔭ᵍ^eᵍ, unique up to order. This is the ideal analogue of the fundamental theorem of arithmetic.',
    example: 'In ℤ[√-5], (6) = (2,1-√-5)²·(3,1+√-5)·(3,1-√-5) — a unique prime ideal factorization despite 6 having two irreducible element factorizations.',
  },

  // ────────────── §5 The factoring algorithm ──────────────
  an55factoringAlgorithm: {
    term: 'Dedekind–Kummer theorem',
    definition: 'For a monogenic number field K = ℚ(θ) with 𝒪_K = ℤ[θ] and minimal polynomial f, the factorization of a prime p into prime ideals mirrors the factorization of f mod p: if f ≡ ∏ f̄ᵢ^eᵢ (mod p) then (p) = ∏ 𝔭ᵢ^eᵢ where 𝔭ᵢ = (fᵢ(θ), p).',
    example: 'In ℤ[i], the minimal polynomial is x²+1. Mod 5: x²+1 = (x+2)(x-2) in 𝔽₅, so (5) = (5,2+i)·(5,2-i) in ℤ[i].',
  },
  an55monogenic: {
    term: 'Monogenic number field',
    definition: 'A number field K where the ring of integers 𝒪_K = ℤ[θ] is generated by a single algebraic integer θ over ℤ. In monogenic fields the Dedekind–Kummer theorem applies to all primes.',
    example: 'ℚ(√-5) is monogenic with 𝒪_K = ℤ[√-5] = ℤ[θ] for θ = √-5. ℚ(∛2) is monogenic with θ = ∛2.',
  },

  // ────────────── §6 Fractional ideals ──────────────
  an55fractionalIdeal: {
    term: 'Fractional ideal',
    symbol: 'J = \\tfrac{1}{x} \\mathfrak{a}',
    definition: 'For a Dedekind domain 𝒜 with fraction field K, a fractional ideal J is a set of the form (1/x)·𝔞 where x ∈ 𝒜 and 𝔞 is an integral ideal. Fractional ideals allow inverses: every integral ideal 𝔞 has a fractional ideal inverse 𝔞⁻¹ with 𝔞·𝔞⁻¹ = 𝒜.',
    example: 'In ℤ, (5/2)ℤ = {5n/2 : n ∈ ℤ} is a fractional ideal with x = 2, 𝔞 = (5). Its inverse is (2/5)ℤ.',
  },
  an55idealGroup: {
    term: 'Ideal group J_K',
    symbol: 'J_K',
    definition: 'The multiplicative group of all nonzero fractional ideals of a number field K (or Dedekind domain). The identity element is (1) = 𝒪_K. Every element factors uniquely as a product of prime ideals with integer (possibly negative) exponents.',
    example: 'In ℤ, J_ℚ consists of all sets (p₁^n₁ ··· pₖ^nₖ)ℤ for primes pᵢ and integers nᵢ ∈ ℤ — just the nonzero fractional multiples of ℤ.',
  },
  an55integralIdeal: {
    term: 'Integral ideal',
    definition: 'An ordinary ideal of 𝒪_K — a fractional ideal with all prime-ideal exponents nonneg. The term "integral ideal" distinguishes these from the more general fractional ideals.',
    example: '(3) = 3𝒪_K and (3,1+√-5) are integral ideals of ℤ[√-5]. The set (1/3)𝒪_K is a fractional but not integral ideal.',
  },

  // ────────────── §7 The ideal norm ──────────────
  an55idealNorm: {
    term: 'Ideal norm 𝒩(𝔞)',
    symbol: '\\mathcal{N}(\\mathfrak{a})',
    definition: 'For a nonzero ideal 𝔞 ⊆ 𝒪_K, the ideal norm is |𝒪_K/𝔞|, the number of cosets of 𝔞 in 𝒪_K. It is always finite. The norm is completely multiplicative: 𝒩(𝔞𝔟) = 𝒩(𝔞)𝒩(𝔟). For principal ideals 𝒩((a)) = |Norm_{K/ℚ}(a)|.',
    example: 'In ℤ[i], 𝒩((2+i)) = |ℤ[i]/(2+i)| = |𝔽₅| = 5. 𝒩((5)) = 25.',
  },
  an55elementNorm: {
    term: 'Element norm Norm_{K/ℚ}(a)',
    symbol: '\\operatorname{Norm}_{K/\\QQ}(a)',
    definition: 'For an element a in a number field K of degree n over ℚ, the norm Norm_{K/ℚ}(a) is the product of all Galois conjugates of a. For a quadratic field ℚ(√d), Norm(a+b√d) = a² - db². Always an integer when a ∈ 𝒪_K.',
    example: 'In ℤ[√-5], Norm(1+√-5) = 1² + 5·1² = 6. Norm(2) = 4. Norm(3) = 9.',
  },
};

export default entries;
