/**
 * Chapter glossary for Part 14 Chapter 6 — Bonus: Let's solve Pell's equation!
 * All keys are prefixed with "an58" to guarantee portal-wide uniqueness.
 */
import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── §1 Units ──────────────
  an58ringOfIntegers: {
    term: 'Ring of integers 𝒪_K',
    symbol: '\\mathcal{O}_K',
    definition: 'For a number field K, the ring of integers 𝒪_K consists of all elements of K that satisfy a monic polynomial with integer coefficients. It generalises ℤ inside ℚ.',
    example: '𝒪_ℚ = ℤ. 𝒪_{ℚ(√3)} = ℤ[√3]. 𝒪_{ℚ(√5)} = ℤ[(1+√5)/2].',
  },
  an58normNK: {
    term: 'Field norm N_{K/ℚ}',
    symbol: '\\NK(\\alpha)',
    definition: 'For α ∈ K, the field norm N_{K/ℚ}(α) is the product of all conjugates of α over ℚ. It lands in ℚ, and in ℤ when α ∈ 𝒪_K. Multiplicative: N(αβ) = N(α)·N(β).',
    example: 'For K = ℚ(√d) and α = a + b√d: N(α) = a² − db². For K = ℚ(i) and α = a + bi: N(α) = a² + b².',
  },
  an58unitGroup: {
    term: 'Unit group 𝒪_K×',
    symbol: '\\mathcal{O}_K^\\times',
    definition: 'The group of invertible elements (units) of the ring of integers 𝒪_K under multiplication. An element α is a unit exactly when its norm N_{K/ℚ}(α) = ±1.',
    example: 'In ℤ[√3], the units include ±(2+√3)ⁿ for all n ∈ ℤ.',
  },
  an58rootOfUnity: {
    term: 'Root of unity',
    definition: 'An element ω such that ωⁿ = 1 for some positive integer n. Every root of unity is a unit in 𝒪_K since its norm must be ±1. Examples: ±1, ±i (in ℤ[i]), and the 6th roots of unity in ℤ[(1+√-3)/2].',
    example: 'In ℤ[i] the roots of unity are ±1 and ±i — the four 4th roots of 1.',
  },
  an58signature: {
    term: 'Signature of a number field',
    symbol: '(r_1, r_2)',
    definition: 'The signature (r₁, r₂) of a number field K of degree n = r₁ + 2r₂ records how many real embeddings (r₁) and conjugate pairs of complex embeddings (r₂) it has. Determines the rank of the unit group via Dirichlet\'s unit theorem.',
    example: 'ℚ(√3) has signature (2, 0) — two real embeddings. ℚ(i) has signature (0, 1) — one conjugate pair.',
  },
  // ────────────── §2 Dirichlet's unit theorem ──────────────
  an58muOK: {
    term: 'Roots of unity μ(𝒪_K)',
    symbol: '\\mu(\\mathcal{O}_K)',
    definition: 'The set of all roots of unity contained in 𝒪_K. It is a finite cyclic subgroup of 𝒪_K×. For most real fields this is just {±1}; imaginary quadratic fields can have more.',
    example: 'μ(ℤ[i]) = {±1, ±i}. μ(ℤ[√3]) = {±1}. μ(ℤ[(1+√−3)/2]) = {z : z⁶ = 1}.',
  },
  an58dirichletUnitTheorem: {
    term: "Dirichlet's unit theorem",
    definition: "For a number field K with signature (r₁, r₂), the unit group 𝒪_K× is isomorphic to ℤ^s × μ(𝒪_K) where s = r₁ + r₂ − 1. There exist s independent fundamental units u₁, …, uₛ such that every unit is uniquely ω·u₁^n₁…uₛ^nₛ for ω a root of unity.",
    example: 'ℚ(√3) has signature (2,0), so s = 1 and 𝒪_K× ≅ ℤ × {±1}; the single fundamental unit is 2+√3.',
  },
  an58fundamentalUnit: {
    term: 'Fundamental unit',
    definition: 'For a real quadratic field K = ℚ(√d) (signature (2,0)), the fundamental unit is the smallest unit u > 1 in 𝒪_K×. Every unit is then ±uⁿ for some n ∈ ℤ. Finding it is the key computational challenge in Dirichlet\'s theorem.',
    example: 'Fundamental unit of ℤ[√2] is 1+√2. Of ℤ[√3] is 2+√3. Of ℤ[√11] is 10+3√11.',
  },
  // ────────────── §3 Finding fundamental units ──────────────
  an58pellEquationPM: {
    term: "Pell-type equation x² − dy² = ±1",
    symbol: 'x^2 - dy^2 = \\pm 1',
    definition: 'A Diophantine equation whose integer solutions correspond to elements a + b√d of norm ±1 in ℤ[√d]. The smallest positive solution (x,y) gives the fundamental unit x + y√d when d ≡ 2, 3 (mod 4).',
    example: 'For d = 3: x² − 3y² = 1 has smallest solution (2,1), giving fundamental unit 2+√3.',
  },
  // ────────────── §4 Pell's equation ──────────────
  an58pellEquation: {
    term: "Pell's equation",
    symbol: 'x^2 - dy^2 = 1',
    definition: 'The classical Diophantine equation x² − dy² = 1 for a positive squarefree integer d. All integer solutions are generated by powers of the fundamental unit of ℚ(√d). The name is a historical misnomer — Pell had little to do with it.',
    example: 'For d = 5: the fundamental unit of ℚ(√5) is (1+√5)/2, and the first integer solution to x² − 5y² = 1 is (9, 4).',
  },
  an58numberField: {
    term: 'Number field',
    definition: 'A finite extension K of ℚ, i.e. a field containing ℚ with [K : ℚ] < ∞. Standard examples are ℚ(√d) (quadratic) and ℚ(∛2) (cubic).',
    example: 'K = ℚ(√5) has degree 2 over ℚ; every element looks like a + b√5 with a, b ∈ ℚ.',
  },
};

export default entries;
