import type { GlossaryEntry } from '../glossary';

// Chapter 71 — "The long exact sequence" (part-18, chapter 02).
// Every key is prefixed `tle71` to stay collision-free with sibling
// chapters authored in parallel elsewhere in this part.
const entries: Record<string, GlossaryEntry> = {
  tle71Exact: {
    term: 'Exact sequence',
    symbol: '\\cdots \\to G_{n+1} \\to G_n \\to G_{n-1} \\to \\cdots',
    definition: 'A sequence of group homomorphisms in which the image of every arrow equals the kernel of the next one. As special cases: 0 → A → B is exact iff A → B is injective, and A → B → 0 is exact iff A → B is surjective.',
  },
  tle71ShortExact: {
    term: 'Short exact sequence',
    symbol: '0 \\to A \\hookrightarrow B \\twoheadrightarrow C \\to 0',
    definition: 'An exact sequence of the form 0 → A → B → C → 0: the first map is injective, the second is surjective, and the image of the first equals the kernel of the second. Informally, C is "B with A collapsed to zero" — think of C as B/A.',
  },
  tle71ChainComplex: {
    term: 'Chain complex',
    symbol: 'C_\\bullet',
    definition: 'A sequence of abelian groups ⋯ → C_{n+1} → C_n → C_{n−1} → ⋯ equipped with boundary maps ∂ satisfying ∂∘∂ = 0 — the boundary of a boundary is always zero.',
  },
  tle71Cycle: {
    term: 'Cycle',
    symbol: '\\partial_n(c) = 0',
    definition: 'An n-chain c with ∂(c) = 0 — a chain with no boundary. Every boundary is automatically a cycle (since ∂∘∂ = 0), but the converse can fail; homology measures exactly that gap.',
  },
  tle71Boundary: {
    term: 'Boundary (chain)',
    symbol: 'c = \\partial(b)',
    definition: 'An n-chain c that equals ∂(b) for some (n+1)-chain b. The boundaries form a subgroup of the cycles, and the homology group is exactly cycles modulo boundaries.',
  },
  tle71Homology: {
    term: 'Homology group',
    symbol: 'H_n(C_\\bullet)',
    definition: 'For a chain complex C•, the group H_n(C•) = (cycles in degree n) / (boundaries in degree n). A chain complex all of whose homology groups vanish is called exact.',
  },
  tle71ChainSES: {
    term: 'Short exact sequence of chain complexes',
    symbol: '0 \\to A_\\bullet \\to B_\\bullet \\to C_\\bullet \\to 0',
    definition: 'A map of chain complexes 0 → A• → B• → C• → 0 that is short exact in every single degree n — meaning 0 → A_n → B_n → C_n → 0 is a short exact sequence of groups for each n, and all the squares with the boundary maps commute.',
  },
  tle71LongExact: {
    term: 'Long exact sequence',
    symbol: '\\cdots \\to H_n(A_\\bullet) \\to H_n(B_\\bullet) \\to H_n(C_\\bullet) \\to H_{n-1}(A_\\bullet) \\to \\cdots',
    definition: 'An infinite exact sequence stitched together from the homology groups of a short exact sequence of chain complexes, connected by maps that drop down one degree every third arrow.',
  },
  tle71ConnectingHom: {
    term: 'Connecting homomorphism',
    symbol: '\\partial \\colon H_n(C_\\bullet) \\to H_{n-1}(A_\\bullet)',
    definition: 'The map in a long exact sequence that drops down one degree and switches complexes. Built by a "left, down, left" procedure: lift a cycle of C to B, apply the boundary map of B, then pull the result back to A.',
  },
  tle71SnakeLemma: {
    term: 'Snake lemma',
    definition: 'A lemma about a commutative diagram of two short exact rows of groups: it produces a six-term exact sequence linking the kernels and cokernels of the vertical maps. Applying it twice is an alternative way to build the long exact sequence.',
  },
  tle71ReducedHomology: {
    term: 'Reduced homology',
    symbol: '\\wt H_n(X)',
    definition: 'A minor variant of homology arranged so that a single point has every group zero: H̃_n(X) agrees with H_n(X) for n ≥ 1, while H̃_0(X) is H_0(X) with one copy of ℤ removed.',
  },
  tle71Augmented: {
    term: 'Augmented chain complex',
    symbol: '\\wt C_\\bullet',
    definition: 'The chain complex C_• with one extra term ℤ appended in degree −1, joined by the augmentation map ε: C_0 → ℤ sending every 0-simplex to 1. Its homology groups are exactly the reduced homology groups.',
  },
  tle71UPlusV: {
    term: 'Chains subordinate to a cover',
    symbol: 'C_n(U+V)',
    definition: 'For an open cover X = U ∪ V, the subgroup of C_n(X) generated by simplices lying entirely inside U or entirely inside V. The open cover theorem says its homology already agrees with that of all of X.',
  },
  tle71MVShortExact: {
    term: 'Mayer–Vietoris short exact sequence',
    symbol: '0 \\to C_\\bullet(U \\cap V) \\to C_\\bullet(U) \\oplus C_\\bullet(V) \\to C_\\bullet(U+V) \\to 0',
    definition: 'For an open cover X = U ∪ V, the short exact sequence of chain complexes sending a chain c of U ∩ V to (c, −c), and a pair (c, d) to c + d. Feeding it into the long exact sequence theorem produces the Mayer–Vietoris sequence.',
  },
  tle71RelChain: {
    term: 'Relative chains',
    symbol: 'C_n(X,A)',
    definition: 'The quotient group C_n(X)/C_n(A) for a subspace A of X: chains of X, with anything supported entirely inside A declared to be zero.',
  },
  tle71RelHomology: {
    term: 'Relative homology',
    symbol: 'H_n(X,A)',
    definition: 'The homology of the relative chain complex C_•(X,A). It measures the n-dimensional holes of X that are not already accounted for by the subspace A.',
  },
  tle71MVLES: {
    term: 'Mayer–Vietoris long exact sequence',
    definition: 'The long exact sequence ⋯ → H_n(U∩V) → H_n(U)⊕H_n(V) → H_n(X) → H_{n−1}(U∩V) → ⋯, obtained by applying the long exact sequence theorem to the Mayer–Vietoris short exact sequence and replacing H_n(U+V) with H_n(X).',
  },
  tle71Contractible: {
    term: 'Contractible',
    definition: 'A space that is homotopy equivalent to a single point — it can be continuously shrunk down to one point within itself. All of its reduced homology groups vanish.',
  },
  tle71HomotopyEquivalent: {
    term: 'Homotopy equivalent',
    symbol: 'X \\simeq Y',
    definition: 'Two spaces X and Y linked by maps f: X→Y and g: Y→X whose two round-trip composites are each homotopic to an identity map. Homotopy equivalent spaces always have isomorphic homology groups, even when they are not homeomorphic.',
  },
  tle71WedgeSum: {
    term: 'Wedge sum',
    symbol: 'X \\vee Y',
    definition: 'The space formed by gluing X and Y together at a single shared point. The figure eight S¹ ∨ S¹ is two circles glued at one point.',
  },
  tle71SplitExact: {
    term: 'Split exact sequence',
    definition: 'A short exact sequence 0 → A → B → C → 0 that "splits": B is isomorphic to A ⊕ C in a way compatible with the maps to and from A and C. This always happens when C is a free abelian group, such as ℤ or ℤⁿ.',
  },
};

export default entries;
