/**
 * Chapter glossary for Part 18 Chapter 70 — Singular homology.
 * All keys prefixed with sh70 to guarantee portal-wide uniqueness
 * (sibling chapters authored in parallel worktrees can't see this file).
 */
import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── §1 Simplices and boundaries ──────────────
  sh70StandardSimplex: {
    term: 'Standard n-simplex',
    symbol: '\\Delta^n',
    definition: 'The set of points (x₀, x₁, …, xₙ) with every xᵢ ≥ 0 and x₀ + x₁ + ⋯ + xₙ = 1. Geometrically it is the convex hull of n+1 vertices v₀, …, vₙ, kept in a fixed order.',
    example: 'Δ⁰ is a single point, Δ¹ is a line segment, Δ² is a (solid, filled-in) triangle, Δ³ is a solid tetrahedron.',
  },
  sh70SingularSimplex: {
    term: 'Singular n-simplex',
    symbol: '\\sigma \\colon \\Delta^n \\to X',
    definition: 'A continuous map from the standard n-simplex into a topological space X. It need not be injective — its image can look "singular" (pinched, folded, self-crossing), which is where the name comes from.',
    example: 'A singular 1-simplex is just a path in X; a singular 0-simplex is just a point of X.',
  },
  sh70Chain: {
    term: 'n-chain',
    symbol: '\\textstyle\\sum_k a_k \\sigma_k',
    definition: 'A formal finite linear combination of singular n-simplices with integer coefficients. Chains are added by combining coefficients on matching simplices, exactly like formal sums of basis vectors.',
    example: 'If σ and τ are singular 1-simplices (paths), then 3σ − τ is a 1-chain.',
  },
  sh70BoundaryOperator: {
    term: 'Boundary operator',
    symbol: '\\partial',
    definition: 'The map sending a singular n-simplex σ = [v₀,…,vₙ] to the alternating sum of its (n−1)-dimensional faces, ∂σ = Σᵢ (−1)ⁱ [v₀,…,v̂ᵢ,…,vₙ] (the hat means "omit this vertex"), extended linearly to chains. By convention a 0-chain has boundary 0.',
    example: 'For a 1-simplex [v₀,v₁] (a directed edge), ∂[v₀,v₁] = [v₁] − [v₀]: the endpoint minus the start point.',
  },

  // ────────────── §2 The singular homology groups ──────────────
  sh70SingularChainComplex: {
    term: 'Singular chain complex',
    symbol: '\\dots \\to C_1(X) \\to C_0(X) \\to 0',
    definition: 'The sequence of chain groups C₀(X), C₁(X), C₂(X), … of a space X together with the boundary maps ∂ between them. It is the algebraic object that every homology computation starts from.',
  },
  sh70Cycle: {
    term: 'Cycle',
    symbol: 'Z_n(X) = \\ker(\\partial \\colon C_n(X) \\to C_{n-1}(X))',
    definition: 'An n-chain with zero boundary — an element of the kernel of ∂: Cₙ(X) → Cₙ₋₁(X). Cycles are the chains that "close up" on themselves.',
    example: 'A loop drawn as a 1-chain, like the loop wrapping around the hole of an annulus, is a cycle: its boundary (start point minus end point) is zero because it returns to where it started.',
  },
  sh70BoundaryGroup: {
    term: 'Boundary (chain group)',
    symbol: 'B_n(X) = \\img(\\partial \\colon C_{n+1}(X) \\to C_n(X))',
    definition: 'An n-chain that is the boundary of some (n+1)-chain — an element of the image of ∂: Cₙ₊₁(X) → Cₙ(X). Every boundary is automatically a cycle, since ∂∘∂ = 0.',
  },
  sh70HomologyGroup: {
    term: 'Homology group',
    symbol: 'H_n(X) \\defeq Z_n(X)/B_n(X)',
    definition: 'The quotient of the cycle group by the boundary group in dimension n. A nonzero element represents a cycle that fails to be a boundary — an algebraic witness of an n-dimensional hole in the space.',
    example: 'For a path-connected space X, H₀(X) ≅ ℤ, and for the annulus, H₁(annulus) ≅ ℤ, generated by a loop around the central hole.',
  },
  sh70DirectSum: {
    term: 'Direct sum (abelian groups)',
    symbol: 'G \\oplus H',
    definition: 'The direct sum of abelian groups, written with ⊕ instead of × — the notational convention used once groups are viewed as ℤ-modules. ℤ^⊕r means r independent copies of ℤ added together.',
    example: 'If a space has r path-connected components, H₀(X) ≅ ℤ^⊕r: one ℤ summand per component.',
  },
  sh70Abelianization: {
    term: 'Abelianization',
    symbol: 'G^{\\mathrm{ab}} = G / [G,G]',
    definition: 'The abelianization of a group G is the largest abelian quotient of G, obtained by quotienting by the commutator subgroup [G,G] (generated by all elements ghg⁻¹h⁻¹). It forces every pair of elements to commute.',
    example: 'The abelianization of the free group ⟨a,b⟩ is ℤ ⊕ ℤ, since forcing ab = ba on two independent generators just leaves independent formal sums.',
  },
  sh70NaturalTransformation: {
    term: 'Natural transformation',
    symbol: '\\phi \\colon F \\Rightarrow G',
    definition: 'Given two functors F, G between the same pair of categories, a natural transformation is a family of morphisms φ_X: F(X) → G(X), one for every object X, such that for every morphism h: X → Y the square built from F(h), G(h), and the two φ maps commutes.',
    example: 'The Hurewicz map φ: π₁(X, x₀) → H₁(X) is natural: for any pointed map h, the induced maps on π₁ and H₁ commute with φ.',
  },
  sh70Contractible: {
    term: 'Contractible',
    definition: 'A space that is homotopy equivalent to a single point — it can be continuously shrunk down to a point within itself. Contractible spaces have no interesting homotopy or homology in positive dimensions.',
    example: 'ℝⁿ is contractible for every n: scale every point toward the origin, continuously, until everything is the origin.',
  },

  // ────────────── §3 The homology functor and chain complexes ──────────────
  sh70ChainComplexAbstract: {
    term: 'Chain complex (abstract)',
    symbol: 'A_\\bullet',
    definition: 'A sequence of abelian groups Aₙ with maps ∂: Aₙ → Aₙ₋₁ such that any two adjacent maps compose to zero. The singular chain complex C•(X) is a specific example built from a topological space.',
  },
  sh70ChainMap: {
    term: 'Chain map',
    symbol: 'f \\colon A_\\bullet \\to B_\\bullet',
    definition: 'A sequence of maps fₙ: Aₙ → Bₙ, one for every n, that commute with the boundary maps of the two chain complexes. Chain maps always send cycles to cycles and boundaries to boundaries, so they induce maps on homology.',
  },
  sh70CmplxCategory: {
    term: 'Category of chain complexes',
    symbol: '\\mathrm{Cmplx}',
    definition: 'The category whose objects are chain complexes and whose morphisms are chain maps.',
  },
  sh70ChainHomotopy: {
    term: 'Chain homotopy',
    symbol: 'g_n - f_n = \\partial_B \\circ P_n + P_{n-1} \\circ \\partial_A',
    definition: 'A family of maps Pₙ: Aₙ → Bₙ₊₁ witnessing that two chain maps f, g: A• → B• are "the same up to boundaries." Chain homotopic maps always induce the same map on homology groups.',
  },
  sh70hTopCategory: {
    term: 'The category hTop',
    symbol: '\\mathrm{hTop}',
    definition: 'The category whose objects are topological spaces and whose morphisms are homotopy classes of continuous maps. Two spaces are isomorphic in hTop exactly when they are homotopy equivalent.',
  },
  sh70PrismOperator: {
    term: 'Prism operator',
    symbol: 'P_n',
    definition: 'Given a homotopy F between f, g: X → Y, the prism operator sends an n-simplex σ in X to an (n+1)-chain in Y, built by splitting the "prism" Δⁿ × [0,1] into n+1 simplices and pushing them into Y via F. It supplies the chain homotopy showing f and g induce the same map on homology.',
  },

  // ────────────── §4 More examples of chain complexes ──────────────
  sh70AugmentedComplex: {
    term: 'Augmented singular chain complex',
    symbol: '\\wt C_\\bullet(X)',
    definition: 'The singular chain complex of a nonempty space X, extended one step further by a map ε: C₀(X) → ℤ sending a formal sum of points to the sum of its coefficients. It amounts to treating ℤ as the group generated by the unique (−1)-simplex.',
  },
  sh70ReducedHomology: {
    term: 'Reduced homology groups',
    symbol: '\\wt H_n(X)',
    definition: 'The homology groups of the augmented chain complex. They agree with ordinary Hₙ(X) for n > 0, but strip out one ℤ summand at n = 0 (the one every path-connected space contributes), so H₀(X) ≅ H̃₀(X) ⊕ ℤ. Convenient because contractible spaces have all reduced homology groups vanish, with no special case at n = 0.',
    example: 'For Sᵐ with m ≥ 1, H̃ₙ(Sᵐ) ≅ ℤ exactly at n = m, and 0 otherwise — cleaner than the unreduced formula, which has an extra ℤ at n = 0.',
  },
  sh70RelativeChainGroup: {
    term: 'Relative chain group',
    symbol: 'C_n(X,A) \\defeq C_n(X)/C_n(A)',
    definition: 'The quotient of the chain group of X by the chain group of a subspace A ⊆ X, so that chains lying entirely inside A become trivial. The boundary map descends to give a relative chain complex.',
  },
  sh70RelativeHomology: {
    term: 'Relative homology group',
    symbol: 'H_n(X,A)',
    definition: 'The homology groups of the relative chain complex C•(X,A). They are not, in general, the same as Hₙ(X)/Hₙ(A) — that naive guess can even fail to typecheck. For nice enough X and A, Hₙ(X,A) turns out to equal the reduced homology H̃ₙ(X/A) of the quotient space, via the excision theorem.',
    example: 'For X = ℝ² and A = S¹, H₁(X) = 0 while H₁(A) = ℤ, so "H₁(X)/H₁(A)" makes no sense — yet H₁(X,A) is still perfectly well defined.',
  },
  sh70MayerVietorisComplex: {
    term: 'Mayer–Vietoris sequence',
    definition: 'A tool built from restricting to chains subordinate to an open cover X = U ∪ V (each simplex landing entirely in U or entirely in V). The resulting homology groups agree with those of X, and comparing chains in U, V, and their overlap yields a long exact sequence relating Hₙ(X), Hₙ(U), Hₙ(V), and Hₙ(U∩V).',
  },
};

export default entries;
