import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── Chapter 34 — Bonus: Topological Abel-Ruffini Theorem ──────────────
  quinticFormula: {
    term: 'Quintic formula',
    definition:
      'A hypothetical formula that takes the five coefficients of a degree-5 polynomial and produces its five roots using only +, −, ×, ÷, and nth roots applied finitely many times. The Abel-Ruffini theorem says no such formula exists.',
    example:
      'The quadratic formula is the analogue for degree-2 polynomials; the cubic and quartic also have formulas. Degree 5 and above do not.',
  },
  radicalExpression: {
    term: 'Radical expression',
    definition:
      'A formula built from the arithmetic operations +, −, ×, ÷ and nth root extractions (√[n]{·}) applied to constants and variables. The Abel-Ruffini theorem states that the roots of a general quintic cannot be expressed as a radical expression in its coefficients.',
    example: 'The quadratic formula x = (−b ± √(b²−4ac)) / 2a is a radical expression in a, b, c.',
  },
  rootPermutation: {
    term: 'Root permutation',
    definition:
      'A rearrangement of the roots z₁, …, z₅ of a polynomial obtained by continuously moving them along smooth paths and tracking which root is which. Such a permutation is an element of the symmetric group S₅.',
    example:
      'Swapping z₁ and z₂ along two non-intersecting arcs is a transposition (12) ∈ S₅ that fixes the coefficients.',
  },
  S5: {
    term: 'Symmetric group on 5 letters',
    symbol: 'S_5',
    definition:
      'The group of all permutations of 5 elements. It has 5! = 120 elements. The key fact driving the topological Abel-Ruffini proof is that S₅ is not solvable — its derived series never reaches the trivial group.',
    example: 'The transposition (12) swapping the first two elements is one of the 10 transpositions in S₅.',
  },
  liftingPath: {
    term: 'Lifting of a path',
    definition:
      'Given a path in the space of polynomial coefficients, a lifting tracks how a chosen branch of a multi-valued function (such as √[n]{R}) moves as the coefficients vary. Different homotopy classes of paths can produce different liftings, causing the function to return a different value after the path completes.',
    example:
      'For the quadratic formula, going around the discriminant causes the two branches ±√(discriminant) to swap — the path lifts to a path that ends at the other root.',
  },
  phaseAccumulation: {
    term: 'Phase accumulation',
    definition:
      'The winding number of a complex-valued path around the origin, measured in multiples of 2π. When a path in coefficient space winds around a branch point of √[n]{R}, the value of √[n]{R} picks up a phase factor e^(2πi/n). This phase is abelian — phases add.',
    example:
      'For a square root, going around the branch point once multiplies the value by e^(iπ) = −1. Going around twice returns to the original value.',
  },
  commutatorGroup: {
    term: 'Commutator',
    symbol: '[a, b] = aba^{-1}b^{-1}',
    definition:
      'For elements a and b of a group, the commutator [a, b] = aba⁻¹b⁻¹ measures how much a and b fail to commute. If G is abelian, every commutator is the identity. The commutator subgroup [G, G] is generated by all commutators.',
    example:
      'In S₃, the transpositions (12) and (23) have commutator (12)(23)(12)⁻¹(23)⁻¹ = (132), a 3-cycle.',
  },
  commutatorSubgroup: {
    term: 'Commutator subgroup',
    symbol: '[G, G]',
    definition:
      'The subgroup [G, G] generated by all commutators aba⁻¹b⁻¹ in G. It is always normal in G, and G/[G,G] is the largest abelian quotient of G. Taking repeated commutator subgroups gives the derived series.',
    example:
      'For G = S₃, [S₃, S₃] = A₃ ≅ ℤ/3ℤ. The quotient S₃/A₃ ≅ ℤ/2ℤ is abelian.',
  },
  derivedSeries: {
    term: 'Derived series',
    symbol: 'G \\supseteq G^{(1)} \\supseteq G^{(2)} \\supseteq \\cdots',
    definition:
      'The chain G = G⁽⁰⁾ ⊇ G⁽¹⁾ = [G,G] ⊇ G⁽²⁾ = [G⁽¹⁾, G⁽¹⁾] ⊇ … obtained by repeatedly taking commutator subgroups. Each term is normal in the previous one and the quotient is abelian.',
    example:
      'For S₄: derived series is S₄ ⊇ A₄ ⊇ V₄ ⊇ {e}, which reaches the trivial group — so S₄ is solvable.',
  },
  solvableGroup: {
    term: 'Solvable group',
    definition:
      'A group G is solvable if its derived series G ⊇ G⁽¹⁾ ⊇ G⁽²⁾ ⊇ … eventually reaches the trivial group. Equivalently, G has a chain of normal subgroups with abelian quotients. Galois theory connects solvable groups to polynomials solvable by radicals.',
    example:
      'S₃ and S₄ are solvable. S₅ is not solvable because A₅ is simple and non-abelian, so the derived series stops at A₅.',
  },
  A5: {
    term: 'Alternating group on 5 letters',
    symbol: 'A_5',
    definition:
      'The subgroup of S₅ consisting of even permutations — those expressible as a product of an even number of transpositions. |A₅| = 60. The key algebraic fact is that A₅ is simple (has no non-trivial normal subgroups) and non-abelian, so S₅ is not solvable.',
    example: 'Every 3-cycle is an even permutation: (abc) = (ab)(ac). So A₅ contains all sixty 3-cycles and 5-cycles in S₅.',
  },
  bringRadical: {
    term: 'Bring radical',
    definition:
      'A function, analogous to nth roots, that can express the roots of the general quintic when added to the arithmetic operations. Named after Erland Samuel Bring. Its existence shows the quintic "nearly" has a formula — but Bring radicals are not considered standard algebraic operations.',
  },
  nestedRadical: {
    term: 'Nested radical',
    definition:
      'A radical expression where radicals appear inside other radicals. The degree of nesting is the maximum depth at which radicals appear within other radicals.',
    example: '∛(√(ab + c) − √d) is a nested radical of degree 2: a square root sits inside a cube root.',
  },
};

export default entries;
