/**
 * Chapter glossary for Part 10 Chapter 1 — Measure spaces.
 */
import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── §1 Letter connotations ──────────────
  measureSpace: {
    term: 'Measure space',
    symbol: '(\\Omega, \\mathcal{A}, \\mu)',
    definition: 'A triple consisting of a set Ω (the sample space), a σ-algebra 𝒜 of measurable subsets, and a measure μ assigning each measurable set a non-negative size.',
    example: 'The real line ℝ with the Borel σ-algebra and Lebesgue measure is the canonical measure space.',
  },
  omega: {
    term: 'World / sample point',
    symbol: '\\omega \\in \\Omega',
    definition: 'A single element of the sample space Ω. In probability theory ω is called a "world" or "outcome" — everything random is determined once ω is fixed.',
    example: 'If Ω is all outcomes of three coin flips, then ω = (H, T, H) is one world.',
  },
  sigmaAlgebra: {
    term: 'σ-algebra',
    symbol: '\\mathcal{A}',
    definition: 'A collection 𝒜 of subsets of Ω that is closed under complements and countable unions, and contains ∅ and Ω. The prefix σ signals the countably-infinite closure condition.',
    example: 'For Ω = ℝ, the Borel σ-algebra ℬ(ℝ) is generated by all open intervals.',
  },
  measure: {
    term: 'Measure',
    symbol: '\\mu \\colon \\mathcal{A} \\to [0, +\\infty]',
    definition: 'A function from a σ-algebra to [0, +∞] satisfying μ(∅) = 0 and countable additivity: the measure of a countable disjoint union equals the sum of the individual measures.',
    example: 'Lebesgue measure on ℝ assigns each interval [a, b] the length b − a.',
  },
  // ────────────── §2 Motivating via random variables ──────────────
  randomVariable: {
    term: 'Random variable',
    symbol: 'X \\colon \\Omega \\to \\mathbb{R}',
    definition: 'A measurable function from the sample space Ω to the reals. Once the world ω is fixed, the value X(ω) is determined. The randomness comes from not knowing which ω occurred.',
    example: 'Let Ω be all possible climates for Saturday. Then X(ω) = high temperature in Boston on Saturday is a random variable.',
  },
  probabilitySpace: {
    term: 'Probability space',
    symbol: '(\\Omega, \\mathcal{A}, \\mu)',
    definition: 'A measure space where the total measure is 1: μ(Ω) = 1. The measure μ is then called a probability measure, and μ(A) is the probability of event A.',
    example: 'A fair coin: Ω = {H, T}, 𝒜 = all subsets, μ({H}) = μ({T}) = 1/2, μ(Ω) = 1.',
  },
  // ────────────── §3 Motivating geometrically ──────────────
  lebesgueMeasure: {
    term: 'Lebesgue measure',
    symbol: '\\lambda',
    definition: 'The standard notion of length/area/volume on ℝⁿ, extended from intervals/rectangles to all Borel-measurable sets. A single point has measure 0; an interval [a,b] has measure b − a.',
    example: 'λ([0,1]) = 1, λ(ℚ ∩ [0,1]) = 0, λ(circle of radius r) = πr² in ℝ².',
  },
  // ────────────── §4 σ-algebras and measurable spaces ──────────────
  measurableSpace: {
    term: 'Measurable space',
    symbol: '(\\Omega, \\mathcal{A})',
    definition: 'A pair of a set Ω and a σ-algebra 𝒜 on it. A measurable space records which subsets are "observable" but assigns no sizes yet — that requires a measure.',
    example: '(ℝ, ℬ(ℝ)) with the Borel σ-algebra is a measurable space. ℝ together with all possible subsets 2^ℝ is also one, but unwieldy.',
  },
  generatedSigmaAlgebra: {
    term: 'σ-algebra generated by a family',
    symbol: '\\sigma(\\mathcal{F})',
    definition: 'For a family ℱ of subsets of Ω, σ(ℱ) is the smallest σ-algebra containing every set in ℱ. It is the intersection of all σ-algebras that contain ℱ.',
    example: 'σ({open sets of ℝ}) = ℬ(ℝ), the Borel σ-algebra.',
  },
  borelSigmaAlgebra: {
    term: 'Borel σ-algebra',
    symbol: '\\mathcal{B}(\\Omega)',
    definition: 'The σ-algebra generated by all open sets of a topological space Ω. Its elements are called Borel sets. For Ω = ℝ it contains all open and closed sets, countable unions and intersections thereof, and much more.',
    example: 'ℬ(ℝ) contains every open interval, every closed set, every half-open interval [a,b), and any countable set.',
  },
  borelSpace: {
    term: 'Borel space',
    symbol: '(\\Omega, \\mathcal{B}(\\Omega))',
    definition: 'A topological space Ω equipped with its Borel σ-algebra as the measurable structure.',
  },
  powerSet: {
    term: 'Power set',
    symbol: '2^\\Omega',
    definition: 'The collection of all subsets of Ω — the largest possible σ-algebra on Ω. On a finite or countably infinite set this is manageable; for uncountable sets like ℝ it is too large to support a useful measure.',
    example: 'For Ω = {a, b, c}, 2^Ω = {∅, {a}, {b}, {c}, {a,b}, {a,c}, {b,c}, {a,b,c}} — 2³ = 8 elements.',
  },
  // ────────────── §5 Measure spaces ──────────────
  countableAdditivity: {
    term: 'Countable additivity',
    symbol: '\\mu\\!\\left(\\bigsqcup_n A_n\\right) = \\sum_n \\mu(A_n)',
    definition: 'A measure μ is countably additive if, for any sequence of pairwise disjoint measurable sets A₁, A₂, …, the measure of their union equals the sum of their individual measures. This extends finite additivity to countably infinite collections.',
    example: 'Lebesgue measure: λ([0,1/2) ∪ [1/2,1)) = λ([0,1/2)) + λ([1/2,1)) = 1/2 + 1/2 = 1.',
  },
  countingMeasure: {
    term: 'Counting measure',
    symbol: '\\mu(A) = |A|',
    definition: 'The measure that assigns to each set A its cardinality — the number of elements. Works on any σ-algebra; particularly natural when Ω is finite or countably infinite.',
    example: 'Counting measure on ℤ: μ({−1, 0, 1}) = 3. μ(ℤ) = ∞.',
  },
  // ────────────── §6 Banach-Tarski ──────────────
  vitaliSet: {
    term: 'Vitali set',
    symbol: 'X',
    definition: 'A non-measurable subset of ℝ (or of the unit circle in ℝ²) constructed using the Axiom of Choice by picking one representative from each equivalence class of points differing by a rational multiple of π. It witnesses that not every subset can be assigned a consistent measure.',
    example: 'The Vitali set on the unit circle: Ω = S¹, equivalence by rotation by rational multiples of π. Any assignment of measure m to X gives μ(Ω) = 0 (if m=0) or ∞ (if m>0).',
  },
  banachTarski: {
    term: 'Banach–Tarski paradox',
    definition: 'A theorem (not truly a paradox) stating that a solid ball in ℝ³ can be decomposed into finitely many pieces and reassembled — by rotations and translations only — into two balls of the same size. The pieces are non-measurable sets; the paradox shows no consistent measure can be defined on all of 2^{ℝ³}.',
    example: 'The "doubling" decomposition uses 5 pieces. It relies on the Axiom of Choice to construct non-measurable sets.',
  },
  // ────────────── §7 Measurable functions ──────────────
  measurableFunction: {
    term: 'Measurable function',
    symbol: 'f \\colon (X, \\mathcal{A}) \\to (Y, \\mathcal{B})',
    definition: 'A function between measurable spaces such that the preimage of every measurable set in Y is measurable in X: f⁻¹(S) ∈ 𝒜 for every S ∈ ℬ. This is the measure-theory analogue of continuity.',
    example: 'Every continuous function between topological spaces equipped with Borel σ-algebras is measurable.',
  },
  indicatorFunction: {
    term: 'Indicator function',
    symbol: '\\mathbf{1}_S',
    definition: 'The function that is 1 on the set S and 0 off it: 𝟏_S(ω) = 1 if ω ∈ S, else 0. It is a measurable function if and only if S is a measurable set.',
    example: '𝟏_{[0,1]}(x) = 1 for 0 ≤ x ≤ 1, and 0 otherwise.',
  },
  // ────────────── §8 Almost everywhere ──────────────
  almostEverywhere: {
    term: 'Almost everywhere / almost surely',
    symbol: '\\text{a.e.}\\;/\\;\\text{a.s.}',
    definition: 'A property holds almost everywhere (a.e.) if the set of points where it fails has measure zero. In probability theory the same idea is called almost surely (a.s.).',
    example: 'The functions f(x) = 0 and g(x) = 𝟏_{ℚ}(x) (the indicator of rationals) are equal almost everywhere on ℝ, since ℚ has Lebesgue measure 0.',
  },
  measureZero: {
    term: 'Measure-zero set',
    symbol: '\\mu(A) = 0',
    definition: 'A measurable set A is a null set (or measure-zero set) if μ(A) = 0. Individual points are null sets in Lebesgue measure. Countable unions of null sets are null.',
    example: 'ℚ has Lebesgue measure 0 in ℝ. The Cantor set has Lebesgue measure 0 despite being uncountable.',
  },
};

export default entries;
