import type { GlossaryEntry } from '../glossary';

// ────────────── Chapter 51 — The Riemann-Roch theorem ──────────────

const entries: Record<string, GlossaryEntry> = {
  // §1 Motivation
  rs51riemannSphere: {
    term: 'Riemann sphere',
    symbol: '\\mathbb{C}_\\infty',
    definition:
      'The complex plane ℂ together with a single point at infinity, written ℂ∞ = ℂ ∪ {∞}. It is the simplest compact Riemann surface, topologically a 2-sphere. Every bounded holomorphic function on ℂ∞ must be constant (Liouville).',
    example: 'A meromorphic function on ℂ that has a pole at ∞ becomes a holomorphic map from ℂ∞ into ℂ with a controlled singularity at ∞.',
  },
  rs51ordP: {
    term: 'Order of a meromorphic function at a point',
    symbol: '\\operatorname{ord}_p(f)',
    definition:
      'For a meromorphic function f at a point p: ord_p(f) = d if f has a zero of multiplicity d at p; ord_p(f) = −d if f has a pole of order d at p; and ord_p(f) = 0 otherwise. Combining poles and zeros into a single signed integer makes divisor arithmetic clean.',
    example: 'If f(z) = (z − 2)³/(z − i)², then ord_2(f) = 3, ord_i(f) = −2, and ord_p(f) = 0 for all other p.',
  },
  rs51LDspace: {
    term: 'Space L(D)',
    symbol: 'L(D)',
    definition:
      'For a divisor D on a Riemann surface X, L(D) is the ℂ-vector space of meromorphic functions f on X satisfying Div(f) ≥ −D — meaning poles are no worse than D allows and zeros are at least as good as D requires. Its dimension ℓ(D) is the key quantity in Riemann-Roch.',
    example: 'L(4·∞) on the Riemann sphere consists exactly of the complex polynomials of degree ≤ 4, so dim L(4·∞) = 5.',
  },
  // §2 Divisors
  rs51divisor: {
    term: 'Divisor',
    symbol: 'D \\colon X \\to \\mathbb{Z}',
    definition:
      'A divisor on a Riemann surface X is a function D: X → ℤ that is nonzero only on a discrete (isolated) set of points. We write it as a formal integer linear combination D = Σ nₚ · p where almost all nₚ = 0. Divisors form an abelian group under pointwise addition.',
    example: 'The expression (−3)·i + (−4)·∞ is a divisor on ℂ∞: it assigns −3 to i, −4 to ∞, and 0 to every other point.',
  },
  rs51divisorGroup: {
    term: 'Group of divisors',
    symbol: '\\operatorname{Div}(X)',
    definition:
      'The abelian group of all divisors on a Riemann surface X, with addition defined pointwise: (D₁ + D₂)(p) = D₁(p) + D₂(p). The zero divisor assigns 0 to every point. On a compact surface every divisor has finite support, so Div(X) is the free abelian group on the points of X.',
    example: 'On ℂ∞, the divisors (2)·0 + (−1)·∞ and (−3)·i + (4)·∞ add to give (2)·0 + (−3)·i + (3)·∞.',
  },
  // §3 Degree of a divisor
  rs51degDiv: {
    term: 'Degree of a divisor',
    symbol: '\\deg D',
    definition:
      'For a divisor D on a compact Riemann surface X, its degree is the integer deg D = Σ_{p ∈ X} D(p). The sum is finite because D has finite support on a compact surface. Degree is a group homomorphism Div(X) → ℤ.',
    example: 'deg((−3)·i + (−4)·∞) = −3 + (−4) = −7. The degree of the zero divisor is 0.',
  },
  // §4 Principal divisors
  rs51principalDiv: {
    term: 'Divisor of a meromorphic function',
    symbol: '\\operatorname{Div}(f)',
    definition:
      'For a meromorphic function f on a Riemann surface X, its divisor Div(f) is defined by Div(f)(p) = ord_p(f) for each p ∈ X. It records all zeros (positive entries) and poles (negative entries) with multiplicity. On a compact surface, Div(f) always has degree 0.',
    example: 'For f(z) = (z−3)²/(z−i) on ℂ∞, Div(f) = 2·3 + (−1)·i + (−1)·∞, which has degree 2−1−1 = 0.',
  },
  rs51principalDivisorDef: {
    term: 'Principal divisor',
    definition:
      'A divisor D on a Riemann surface X is called principal if D = Div(f) for some meromorphic function f on X. Principal divisors always have degree 0 on compact surfaces. The analogy with principal ideals (generated by one element) in ring theory is intentional.',
    example: 'Div((z−3)²/(z−i)) = 2·3 + (−1)·i + (−1)·∞ is principal. A divisor of degree −1 cannot be principal on a compact surface.',
  },
  rs51divisorOrder: {
    term: 'Partial order on divisors',
    symbol: 'D_1 \\geq D_2',
    definition:
      'For divisors D₁ and D₂ on a Riemann surface X, we write D₁ ≥ D₂ if D₁(p) ≥ D₂(p) for all p ∈ X. We write D ≥ 0 if D(p) ≥ 0 for every p — meaning D has no negative entries, so it only records zeros, not poles.',
    example: '3·p ≥ 2·p ≥ 0 for any point p. The divisor (−1)·q is not ≥ 0.',
  },
  // §5 Riemann-Roch
  rs51genus: {
    term: 'Genus of a Riemann surface',
    symbol: 'g',
    definition:
      'A topological invariant of a compact Riemann surface X counting its "number of holes." The sphere has genus 0, a torus has genus 1, and a surface with k handles has genus k. The genus appears in the Riemann-Roch formula as the correction term between the degree of D and dim L(D).',
    example: 'The Riemann sphere ℂ∞ has genus 0. An elliptic curve (complex torus) has genus 1.',
  },
  rs51canonicalDiv: {
    term: 'Canonical divisor',
    symbol: 'K',
    definition:
      'A divisor K on a compact Riemann surface X associated with the space of holomorphic 1-forms (meromorphic differentials). Its linear equivalence class — the canonical class — is intrinsic to X and satisfies deg K = 2g − 2 where g is the genus. In Riemann-Roch, K plays the role of a "dual" divisor to D.',
    example: 'On the Riemann sphere (genus 0), the canonical divisor has degree 2·0 − 2 = −2, so K = −2·p for any point p. On a torus (genus 1), deg K = 0.',
  },
  rs51riemannRoch: {
    term: 'Riemann-Roch theorem',
    symbol: '\\dim L(D) - \\dim L(K-D) = \\deg D + 1 - g',
    definition:
      'For a divisor D on a compact algebraic curve (Riemann surface) X of genus g with canonical divisor K: dim L(D) − dim L(K − D) = deg(D) + 1 − g. This formula computes the dimension of the space of meromorphic functions with poles bounded by D, up to a correction term involving L(K − D).',
    example: 'On the sphere (g = 0, K = −2·∞): dim L(4·∞) − dim L(−6·∞) = 4 + 1 − 0 = 5. Since deg(−6·∞) < 0, dim L(−6·∞) = 0, confirming dim L(4·∞) = 5.',
  },
  rs51ellD: {
    term: 'ℓ(D)',
    symbol: '\\ell(D)',
    definition:
      'The dimension of the vector space L(D) over ℂ, also written dim L(D). The Riemann-Roch theorem gives a formula for ℓ(D) in terms of the degree of D, the genus g, and ℓ(K − D). When deg D is large relative to g, the correction term ℓ(K − D) vanishes and ℓ(D) = deg D + 1 − g.',
    example: 'On the Riemann sphere with D = n·∞ (n ≥ 0): ℓ(n·∞) = n + 1, matching the n+1 monomials 1, z, …, zⁿ.',
  },
};

export default entries;
