import type { GlossaryEntry } from '../glossary';

// Chapter 64 — Fundamental groups. All keys prefixed `fg64` to stay unique
// while three Part XVI chapters are authored in parallel.
const entries: Record<string, GlossaryEntry> = {
  // ────────────── §1 — Fusing paths together ──────────────
  fg64PathConcatenation: {
    term: 'Path concatenation (fusing)',
    symbol: '\\gamma_1 \\ast \\gamma_2',
    definition:
      'Given paths γ₁, γ₂: [0,1] → X with γ₁(1) = γ₂(0), the fused path γ₁∗γ₂ runs γ₁ at double speed on [0, 1/2] and then γ₂ at double speed on [1/2, 1]. It is the operation underlying the fundamental group.',
  },
  fg64PathHomotopy: {
    term: 'Path homotopy',
    symbol: 'F \\colon [0,1]^2 \\to X',
    definition:
      'A continuous deformation between two paths α, β: [0,1] → X that keeps both endpoints fixed throughout the deformation. Two paths related this way are path-homotopic, written α ≃ β; this is stronger than ordinary homotopy of maps, which allows endpoints to move.',
  },

  // ────────────── §2 — Fundamental groups ──────────────
  fg64Loop: {
    term: 'Loop',
    symbol: '\\gamma(0) = \\gamma(1) = x_0',
    definition:
      'A path γ: [0,1] → X with γ(0) = γ(1). The shared start/end point x₀ is the basepoint of the loop. Loops are the building blocks of the fundamental group, since a fixed basepoint means we never have to track endpoints when fusing them.',
  },
  fg64ConstantLoop: {
    term: 'Constant ("do-nothing") loop',
    symbol: '1',
    definition:
      'The loop at x₀ that stands still the whole time: 1(t) = x₀ for every t. It plays the role of the identity element in the fundamental group.',
  },
  fg64NulHomotopic: {
    term: 'Null-homotopic',
    symbol: '\\gamma \\simeq 1',
    definition:
      'A loop γ is null-homotopic if it is path-homotopic to the constant loop — it can be continuously "reeled in" to a point without leaving the space.',
  },
  fg64ReversePath: {
    term: 'Reverse path',
    symbol: '\\overline{\\alpha}',
    definition:
      'For a path α: [0,1] → X, the reverse path is ᾱ(t) = α(1−t) — the same route traveled backwards. It starts where α ends and ends where α starts, and serves as the inverse operation for path concatenation.',
  },
  fg64FundamentalGroup: {
    term: 'Fundamental group',
    symbol: '\\pi_1(X, x_0)',
    definition:
      'The set of path-homotopy classes [γ] of loops at a basepoint x₀ in X, equipped with ∗ as the group operation. The identity is the class of the constant loop; the inverse of [γ] is [γ̄].',
    example: 'π₁(ℂ) is trivial. π₁(ℂ∖{0}) ≅ ℤ, generated by a loop that winds once counterclockwise around the puncture.',
  },
  fg64WindingNumber: {
    term: 'Winding number',
    definition:
      'For a loop in ℂ∖{0}, the (signed) number of times it circles the puncture counterclockwise. Winding number is exactly the isomorphism π₁(ℂ∖{0}) ≅ ℤ: homotopic loops have the same winding number, and every integer is achieved.',
  },

  // ────────────── §3 — Homeomorphism invariance ──────────────
  fg64PointedMap: {
    term: 'Pointed map',
    symbol: 'f \\colon (X, x_0) \\to (Y, y_0)',
    definition:
      'Shorthand meaning f: X → Y is a continuous function of spaces that also sends the basepoint x₀ to the basepoint y₀. A "pointed space" is a space together with a chosen basepoint.',
  },
  fg64InducedHomomorphism: {
    term: 'Induced map on loops',
    symbol: 'f_\\sharp',
    definition:
      'For a pointed map f: (X, x₀) → (Y, y₀), the induced map f♯ sends a loop γ at x₀ to the loop f∘γ at y₀. It sends homotopic loops to homotopic loops, so it descends to a group homomorphism π₁(X, x₀) → π₁(Y, y₀).',
  },

  // ────────────── §4 — Higher homotopy groups ──────────────
  fg64HigherHomotopyGroup: {
    term: 'Higher homotopy group',
    symbol: '\\pi_n(X)',
    definition:
      'For n ≥ 1, πₙ(X) is the set of homotopy classes of maps Sⁿ → X, with a group operation generalizing path concatenation. π₁ recovers the fundamental group (loops are the same as maps S¹ → X). πₙ is abelian for every n ≥ 2, unlike π₁.',
  },

  // ────────────── §5 — Homotopy equivalent spaces ──────────────
  fg64HomotopyEquivalence: {
    term: 'Homotopy equivalence',
    definition:
      'Spaces X and Y are homotopy equivalent if there are continuous f: X → Y and g: Y → X with f∘g homotopic to the identity on Y and g∘f homotopic to the identity on X. A more generous notion of "the same shape" than homeomorphism — it allows collapsing whole regions to a point.',
  },
  fg64Contractible: {
    term: 'Contractible space',
    definition:
      'A space that is homotopy equivalent to a single point. Intuitively, the whole space can be continuously shrunk down to one point without leaving the space.',
    example: 'ℂ is contractible (shrink everything toward 0). A disk is contractible. An annulus is not — it is homotopy equivalent to a circle instead.',
  },
  fg64PuncturedPlane: {
    term: 'Punctured plane',
    symbol: '\\mathbb{C} \\setminus \\{0\\}',
    definition:
      'The complex plane with the origin removed. It is homotopy equivalent (but not homeomorphic) to the circle S¹: the inclusion S¹ ↪ ℂ∖{0} and the map z ↦ z/|z| witness the equivalence.',
  },

  // ────────────── §6 — The pointed homotopy category ──────────────
  fg64Category: {
    term: 'Category',
    definition:
      'A collection of objects together with, for every ordered pair of objects, a set of morphisms (arrows) between them, plus a way to compose morphisms associatively, plus an identity morphism at every object. Groups form a category (Grp): objects are groups, morphisms are homomorphisms. Topological spaces form a category (Top): objects are spaces, morphisms are continuous maps.',
  },
  fg64Functor: {
    term: 'Functor',
    definition:
      'A structure-preserving map between categories: it sends objects to objects and morphisms to morphisms, in a way that respects composition and identities. If two objects are isomorphic in the source category, a functor automatically sends them to isomorphic objects in the target category.',
    example: 'π₁ is a functor from the pointed homotopy category to Grp: it sends a pointed space to its fundamental group, and a pointed map f to the induced homomorphism f♯.',
  },
  fg64PointedHomotopyCategory: {
    term: 'Pointed homotopy category',
    symbol: '\\mathbf{hTop}_\\ast',
    definition:
      'The category whose objects are pointed spaces (X, x₀) and whose morphisms (X,x₀) → (Y,y₀) are homotopy classes of continuous based maps. Two path-connected spaces are isomorphic in this category exactly when they are homotopy equivalent.',
  },

  // ────────────── §7 — Problems ──────────────
  fg64SeifertVanKampen: {
    term: 'Seifert–van Kampen theorem',
    definition:
      'If X = U ∪ V for open, path-connected U, V with U ∩ V nonempty and path-connected, this theorem computes π₁(X) from π₁(U), π₁(V), and π₁(U ∩ V) — roughly, π₁(X) is built by gluing π₁(U) and π₁(V) along the shared subgroup coming from π₁(U ∩ V). The special case where π₁(U) and π₁(V) are both trivial says π₁(X) is trivial too.',
  },
};

export default entries;
