/**
 * Glossary entries for Chapter 56 — Minkowski bound and class groups.
 * All keys are prefixed with `an56` to guarantee portal-wide uniqueness.
 */
import type { GlossaryEntry } from '../glossary';

const entries: Record<string, GlossaryEntry> = {
  // ────────────── Chapter 56 — Minkowski bound and class groups ──────────────

  an56fractionalIdeal: {
    term: 'Fractional ideal',
    symbol: '\\mathfrak{a} \\subseteq K',
    definition:
      'A nonzero 𝒪_K-submodule 𝔞 of K such that d𝔞 ⊆ 𝒪_K for some nonzero d ∈ ℤ. Ordinary ideals of 𝒪_K are fractional ideals with d = 1. The set of all fractional ideals forms a group J_K under multiplication.',
    example:
      'In ℤ, the fractional ideal (1/2) = {n/2 : n ∈ ℤ} is not an ordinary ideal of ℤ, but d·(1/2) = (1) ⊆ ℤ when d = 2.',
  },

  an56principalFractionalIdeal: {
    term: 'Principal fractional ideal',
    symbol: '(x) = x\\mathcal{O}_K',
    definition:
      'A fractional ideal of the form x·𝒪_K for some x ∈ K×. Every such ideal is generated by a single element of the field. The set of all principal fractional ideals P_K is a subgroup of J_K.',
    example: '(3/2) = (3/2)ℤ is a principal fractional ideal of ℚ.',
  },

  an56classGroup: {
    term: 'Class group (ideal class group)',
    symbol: '\\operatorname{Cl}_K',
    definition:
      'The quotient group J_K / P_K, where J_K is the group of fractional ideals of 𝒪_K and P_K is the subgroup of principal fractional ideals. Two ideals are in the same class if and only if they differ by multiplication by a nonzero element of K. 𝒪_K is a PID exactly when Cl_K is trivial.',
    example:
      'For K = ℚ(√−5), the class group has order 2: every ideal class is either principal or in the unique nontrivial class containing (2, 1 + √−5).',
  },

  an56classNumber: {
    term: 'Class number',
    symbol: 'h_K = |\\operatorname{Cl}_K|',
    definition:
      'The order (size) of the class group Cl_K. It is always a positive integer (the class group is finite). h_K = 1 if and only if 𝒪_K is a PID (hence a UFD). Larger h_K means 𝒪_K is "further" from unique factorization.',
    example:
      'ℚ(i) has class number 1 (ℤ[i] is a UFD). ℚ(√−5) has class number 2. ℚ(√−23) has class number 3.',
  },

  an56discriminant: {
    term: 'Discriminant of a number field',
    symbol: '\\Delta_K',
    definition:
      'For a number field K of degree n with ring of integers 𝒪_K, choose a ℤ-basis α₁, …, αₙ. The discriminant is Δ_K = det[σᵢ(αⱼ)]² where σ₁, …, σₙ are the n embeddings K ↪ ℂ. It is always a nonzero integer independent of the choice of basis. It measures the "volume" of the lattice 𝒪_K sits in.',
    example:
      'For K = ℚ(√2): Δ_K = 8. For K = ℚ(i): Δ_K = −4. For K = ℚ(√5): Δ_K = 5.',
  },

  an56signature: {
    term: 'Signature of a number field',
    symbol: '(r_1, r_2)',
    definition:
      'The pair (r₁, r₂) where r₁ is the number of real embeddings K ↪ ℝ and r₂ is the number of conjugate pairs of complex embeddings K ↪ ℂ. Always r₁ + 2r₂ = [K:ℚ]. The signature determines the shape of the lattice 𝒪_K in ℝⁿ.',
    example:
      'ℚ has signature (1, 0). ℚ(√2) has signature (2, 0). ℚ(i) has signature (0, 1). ℚ(∛2) has signature (1, 1).',
  },

  an56canonicalEmbedding: {
    term: 'Canonical embedding',
    symbol: '\\iota\\colon K \\hookrightarrow \\mathbb{R}^{r_1} \\times \\mathbb{C}^{r_2}',
    definition:
      'The embedding that sends α ∈ K to (σ₁(α), …, σ_{r₁}(α), σ_{r₁+1}(α), …, σ_{r₁+r₂}(α)), listing the r₁ real embeddings and one from each conjugate pair of complex embeddings. Composing with the isomorphism ℝ^{r₁} × ℂ^{r₂} ≅ ℝⁿ gives a lattice for 𝒪_K.',
    example:
      'For K = ℚ(∛2) with signature (1,1), the canonical embedding sends α to (σ₁(α), σ₂(α)) ∈ ℝ × ℂ.',
  },

  an56meshLattice: {
    term: 'Mesh (fundamental volume) of a lattice',
    symbol: '\\mathrm{mesh}(L)',
    definition:
      'The hypervolume of the fundamental parallelepiped of a lattice L in ℝⁿ, equal to the absolute value of the determinant of any matrix whose columns are a basis for L. Under the canonical embedding, 𝒪_K has mesh (1/2^{r₂})√|Δ_K|.',
    example:
      'The lattice ℤ² in ℝ² has mesh 1 (unit square). The lattice ℤ[√2] embedded in ℝ² has mesh 2√2.',
  },

  an56minkowskiThm: {
    term: "Minkowski's theorem",
    definition:
      'If S ⊆ ℝⁿ is convex, centrally symmetric (x ∈ S ⇔ −x ∈ S), and has volume strictly greater than 2ⁿ times the mesh of a lattice L, then S contains a nonzero lattice point of L. The compact case allows equality.',
    example:
      'A circle of area > 4 centered at the origin in ℝ² always contains a nonzero integer lattice point.',
  },

  an56minkowskiBound: {
    term: 'Minkowski bound',
    symbol: 'M_K',
    definition:
      'The constant M_K = (4/π)^{r₂} · (n!/nⁿ) · √|Δ_K|, where (r₁, r₂) is the signature of K and n = [K:ℚ]. Every ideal class of 𝒪_K contains an integral ideal of norm at most M_K. This reduces class group computation to finitely many prime ideals.',
    example:
      'For K = ℚ(i) with (r₁, r₂) = (0,1) and Δ_K = −4: M_K = (4/π)·(2!/4)·2 = 4/π < 2, so Cl_K is trivial.',
  },

  an56trapBox: {
    term: 'Trap box (mousetrap set)',
    symbol: 'S_M',
    definition:
      'The set of (x₁,…,x_{r₁}, z₁,…,z_{r₂}) ∈ ℝ^{r₁} × ℂ^{r₂} satisfying Σ|xᵢ| + 2Σ|zⱼ| ≤ M. It is convex, compact, and centrally symmetric. Any α ∈ 𝒪_K whose canonical image falls in S_M satisfies |N(α)| ≤ (M/n)ⁿ by AM-GM.',
    example:
      'For K = ℚ(√2) with signature (2,0), the trap box is a diamond {(x,y) : |x| + |y| ≤ M} in ℝ².',
  },

  an56numberField: {
    term: 'Number field',
    symbol: 'K = \\mathbb{Q}(\\alpha)',
    definition:
      'A finite extension of ℚ. Every number field can be written ℚ(α) for some algebraic number α. Its degree [K:ℚ] = n equals the dimension of K as a ℚ-vector space, and equals the number of distinct embeddings K ↪ ℂ.',
    example:
      'ℚ(√2) is a degree-2 number field. ℚ(∛2) is degree 3. ℚ(ζₙ), the cyclotomic field, has degree φ(n).',
  },

  an56ringOfIntegers: {
    term: 'Ring of integers',
    symbol: '\\mathcal{O}_K',
    definition:
      'The ring of all algebraic integers inside a number field K. It is a free ℤ-module of rank n = [K:ℚ] and a Dedekind domain. It generalizes ℤ inside ℚ: 𝒪_ℚ = ℤ.',
    example:
      '𝒪_{ℚ(√2)} = ℤ[√2]. 𝒪_{ℚ(i)} = ℤ[i]. 𝒪_{ℚ(√5)} = ℤ[(1+√5)/2] (not ℤ[√5]).',
  },

  an56idealNorm: {
    term: 'Norm of an ideal',
    symbol: '\\operatorname{N}(\\mathfrak{a}) = |\\mathcal{O}_K/\\mathfrak{a}|',
    definition:
      'For a nonzero integral ideal 𝔞 ⊆ 𝒪_K, the norm N(𝔞) = |𝒪_K/𝔞| is the size of the quotient ring. It is always a positive integer. For a prime ideal 𝔭 lying over a rational prime p, N(𝔭) is a power of p.',
    example:
      'In ℤ[i], N((2+i)) = |ℤ[i]/(2+i)| = 5, because the Gaussian prime 2+i lies over 5 and N_{ℚ(i)/ℚ}(2+i) = 5.',
  },

  an56heegnerNumbers: {
    term: 'Heegner numbers',
    definition:
      'The nine positive integers n for which ℚ(√−n) has class number 1: n = 1, 2, 3, 7, 11, 19, 43, 67, 163. These are the only imaginary quadratic fields with unique factorization in their ring of integers.',
    example:
      'ℚ(√−163) has class number 1, and its ring of integers ℤ[(1+√−163)/2] is a UFD. This is the largest Heegner number.',
  },
};

export default entries;
