/**
 * Glossary of mathematical notation used across the portal.
 *
 * Each entry is keyed by a short stable identifier (used as the URL anchor
 * on /glossary and as the `key` prop of the <Term> wrapper component).
 *
 * Style:
 * - `term`: human-readable name. Plain text only — appears in the tooltip header.
 * - `symbol`: optional KaTeX source for the canonical symbol (rendered on the
 *   /glossary page; not in the tooltip).
 * - `definition`: plain text, 1–3 sentences. Appears in the tooltip and on
 *   the /glossary page. NO KaTeX in the tooltip — use unicode (ℤ, ℝ, ℂ, etc.)
 *   or describe in words.
 * - `example`: optional plain-text example, also tooltip-safe.
 *
 * Add new entries here when authoring content; reference them via
 * `<Term key="..."> ... </Term>` in MDX.
 */

export interface GlossaryEntry {
  term: string;
  symbol?: string;
  definition: string;
  example?: string;
}

export const glossary = {
  // ────────────── Number sets ──────────────
  ZZ: {
    term: 'Integers',
    symbol: '\\ZZ',
    definition: 'The integers: …, −2, −1, 0, 1, 2, …. Written with the blackboard-bold ℤ.',
  },
  NN: {
    term: 'Natural numbers',
    symbol: '\\NN',
    definition: 'The natural numbers. In Napkin this includes 0: 0, 1, 2, 3, …',
  },
  QQ: {
    term: 'Rational numbers',
    symbol: '\\QQ',
    definition: 'The rationals: every fraction a/b where a and b are integers and b ≠ 0.',
  },
  RR: {
    term: 'Real numbers',
    symbol: '\\RR',
    definition: 'The real numbers: every point on the number line, including irrationals like √2 and π.',
  },
  CC: {
    term: 'Complex numbers',
    symbol: '\\CC',
    definition: 'The complex numbers, of the form a + bi where a, b are real and i² = −1.',
  },
  Qtimes: {
    term: 'Non-zero rationals',
    symbol: '\\QQ^\\times',
    definition: 'The rationals with 0 removed. The superscript × means "drop the elements that have no multiplicative inverse" — for ℚ that means just dropping 0.',
  },

  // ────────────── Group structure ──────────────
  identity: {
    term: 'Group identity',
    symbol: '1_G',
    definition: 'The identity element of a group G — the element that, combined with any g, gives back g. The subscript names which group\'s identity it is. Sometimes written 0_G when the operation is additive.',
  },
  inverse: {
    term: 'Group inverse',
    symbol: 'g^{-1}',
    definition: 'The inverse of g: the unique element that combines with g to give the identity. The −1 superscript is just notation; for (ℚ×, ·) it really is 1/x, but for a general group it just means "the inverse".',
  },
  power: {
    term: 'Group power',
    symbol: 'g^n',
    definition: 'g combined with itself n times under the group operation. For n = 0 this is the identity; for negative n it means (g⁻¹)^|n|.',
  },
  star: {
    term: 'Generic group operation',
    symbol: '\\star',
    definition: 'A placeholder for "any binary operation" — used instead of + or · to emphasise the operation could be anything.',
  },
  groupOrder: {
    term: 'Order of a group',
    symbol: '|G|',
    definition: 'The number of elements in the group G. May be infinite, e.g. |ℤ| = ∞.',
  },
  elementOrder: {
    term: 'Order of an element',
    symbol: '\\ord g',
    definition: 'The smallest positive integer n with g^n equal to the identity. ∞ if no such n exists.',
  },
  generated: {
    term: 'Subgroup generated by an element',
    symbol: '\\langle x \\rangle',
    definition: 'The smallest subgroup containing x — namely all integer powers of x: …, x⁻², x⁻¹, 1, x, x², …',
  },
  isomorphic: {
    term: 'Isomorphic',
    symbol: '\\cong',
    definition: '"Is isomorphic to" — there exists a structure-preserving bijection between two groups. Treat them as the same group with different names for elements.',
  },

  // ────────────── Specific groups ──────────────
  Zc: {
    term: 'Cyclic group of order n',
    symbol: '\\Zc{n}',
    definition: 'Clock arithmetic: the integers mod n, written ℤ/nℤ. Elements are {0, 1, …, n−1}; addition wraps around at n. ℤ/12ℤ is a 12-hour clock.',
  },
  Zm: {
    term: 'Multiplicative group mod p',
    symbol: '\\Zm{p}',
    definition: 'For a prime p: the non-zero residues {1, 2, …, p−1} under multiplication mod p. The primality is what guarantees every element has a multiplicative inverse.',
  },
  Sn: {
    term: 'Symmetric group',
    symbol: 'S_n',
    definition: 'All permutations (re-orderings) of {1, 2, …, n} under composition. Has n! elements; non-abelian for n ≥ 3.',
  },
  Dn: {
    term: 'Dihedral group',
    symbol: 'D_{2n}',
    definition: 'Symmetries of a regular n-gon — n rotations and n reflections, 2n elements total. Non-abelian for n ≥ 3.',
  },
  GLn: {
    term: 'General linear group',
    symbol: '\\GL_n(\\RR)',
    definition: 'Invertible n×n real matrices, under matrix multiplication. The "general linear group of degree n over ℝ".',
  },
  SLn: {
    term: 'Special linear group',
    symbol: '\\SL_n(\\RR)',
    definition: 'n×n real matrices with determinant 1, under matrix multiplication. A subgroup of GLₙ(ℝ).',
  },
  Q8: {
    term: 'Quaternion group',
    symbol: 'Q_8',
    definition: 'A non-abelian group of order 8, with elements ±1, ±i, ±j, ±k satisfying i² = j² = k² = ijk = −1.',
  },
  Mat: {
    term: 'Set of n×n matrices',
    symbol: '\\Mat_{n \\times n}(\\RR)',
    definition: 'All n×n real matrices (not just invertible ones). Used as a non-example: not a group under multiplication because the zero matrix has no inverse.',
  },
  S1: {
    term: 'Complex unit circle',
    symbol: 'S^1',
    definition: 'The complex numbers of absolute value 1: {z ∈ ℂ : |z| = 1}. Under multiplication this is a group.',
  },
  trivial: {
    term: 'Trivial group',
    symbol: '\\{1\\}',
    definition: 'The group with a single element — just the identity. Often written {1} or {1_G}.',
  },

  // ────────────── Mod-arithmetic notation ──────────────
  pmod: {
    term: 'Modulo',
    symbol: '\\pmod{n}',
    definition: '"Modulo n" — equality up to multiples of n. e.g. 7 ≡ 1 (mod 3) means 7 and 1 differ by a multiple of 3.',
  },
  bar: {
    term: 'Residue class',
    symbol: '\\overline{a}',
    definition: 'The residue class of a mod n: a together with everything that differs from a by a multiple of n. So in ℤ/3ℤ, ̄2 = {…, −1, 2, 5, 8, …}.',
  },
  divides: {
    term: 'Divides',
    symbol: 'a \\mid b',
    definition: '"a divides b" — there is an integer k with b = ka. So 3 ∣ 12 (since 12 = 3·4) but 3 ∤ 7.',
  },
  congruent: {
    term: 'Congruent',
    symbol: '\\equiv',
    definition: '"Is congruent to" — usually paired with (mod n). a ≡ b (mod n) means n divides (a − b).',
  },

  // ────────────── Set / function notation ──────────────
  in: {
    term: 'Element of',
    symbol: '\\in',
    definition: '"Is an element of". x ∈ S means x is in the set S.',
  },
  setbuilderBar: {
    term: 'Such that (in set-builder)',
    symbol: '\\{ x \\in S \\mid P(x) \\}',
    definition: 'Inside set-builder braces, the | (or :) is read "such that". {z ∈ ℂ ∣ |z|=1} is "the z in ℂ such that |z|=1".',
  },
  to: {
    term: 'Function arrow',
    symbol: 'f \\colon A \\to B',
    definition: 'f is a function from A to B. A is the domain, B the codomain.',
  },
  mapsto: {
    term: 'Maps to',
    symbol: 'x \\mapsto y',
    definition: 'Specifies what a function does to inputs. f(x) = x² can be written x ↦ x².',
  },
  subset: {
    term: 'Subset',
    symbol: '\\subseteq',
    definition: '"Is a subset of" (allows equality). For strict-subset use ⊊.',
  },
  emptyset: {
    term: 'Empty set',
    symbol: '\\varnothing',
    definition: 'The set with no elements. Sometimes written ∅ or {}.',
  },

  // ────────────── Metric topology (Chapter 2) ──────────────
  metricSpace: {
    term: 'Metric space',
    symbol: '(M, d)',
    definition: 'A pair consisting of a set M and a distance function d that satisfies symmetry, positive-definiteness, and the triangle inequality.',
  },
  metric: {
    term: 'Metric',
    symbol: 'd \\colon M \\times M \\to \\RR_{\\ge 0}',
    definition: 'The distance function on a metric space. Takes two points and returns a non-negative real number — their "distance".',
  },
  triangleIneq: {
    term: 'Triangle inequality',
    symbol: 'd(x,z) \\le d(x,y) + d(y,z)',
    definition: 'A metric axiom: going via a third point z is never shorter than going directly from x to y.',
  },
  positiveDef: {
    term: 'Positive-definite',
    definition: 'For a metric d: d(x,y) ≥ 0, with equality if and only if x = y. (Zero distance ⇒ same point.)',
  },
  euclideanMetric: {
    term: 'Euclidean metric',
    symbol: 'd(x, y) = \\sqrt{\\sum (x_i - y_i)^2}',
    definition: 'The standard "straight-line distance" on ℝⁿ — square root of the sum of squared coordinate differences.',
  },
  taxicabMetric: {
    term: 'Taxicab metric',
    symbol: 'd(x, y) = \\sum |x_i - y_i|',
    definition: 'A metric on ℝⁿ: the sum of absolute coordinate differences. Equals the path length you\'d travel on a city grid.',
  },
  discreteMetric: {
    term: 'Discrete metric',
    definition: 'A metric on any set: d(x,y) = 0 if x = y, otherwise d(x,y) = 1. Every two distinct points are exactly 1 apart.',
  },
  RRn: {
    term: 'n-dimensional Euclidean space',
    symbol: '\\RR^n',
    definition: 'The set of ordered n-tuples of real numbers, with the Euclidean metric.',
  },
  openBall: {
    term: 'Open unit ball',
    symbol: 'B^n',
    definition: 'The set of points (x₁, …, xₙ) in ℝⁿ with x₁² + ⋯ + xₙ² < 1. Strict inequality — boundary is excluded.',
  },
  unitSphere: {
    term: 'Unit sphere',
    symbol: 'S^{n-1}',
    definition: 'The set of points in ℝⁿ at distance exactly 1 from the origin. The superscript n−1 is the intrinsic dimension (the surface of an n-ball).',
  },
  rNeighborhood: {
    term: 'r-neighborhood',
    symbol: 'M_r(p)',
    definition: 'The set of all points within distance r of p in a metric space. Also called an open ball of radius r centred at p.',
  },
  convergence: {
    term: 'Convergence',
    definition: 'A sequence (xₙ) converges to x if for every ε > 0, all but finitely many terms are within ε of x. The choice of metric matters!',
  },
  continuous: {
    term: 'Continuous map',
    definition: 'A function f between metric spaces is continuous at p if small changes in input give small changes in output — formally, the ε–δ definition.',
  },
  homeomorphism: {
    term: 'Homeomorphism',
    definition: 'A continuous bijection whose inverse is also continuous. Two spaces with one between them are "topologically the same".',
  },
  openSet: {
    term: 'Open set',
    definition: 'A subset U of a metric space such that every point of U has a (small enough) neighborhood entirely inside U.',
  },
  closedSet: {
    term: 'Closed set',
    definition: 'A subset whose complement is open. Equivalently, a set containing all its limit points.',
  },
  limitPoint: {
    term: 'Limit point',
    symbol: '\\lim S',
    definition: 'A point p of a metric space M is a limit point of S ⊆ M if some sequence in S converges to p. The set of all such p is written lim S.',
  },
  closure: {
    term: 'Closure',
    symbol: '\\overline{S}',
    definition: 'The closure of S in M: the set of all limits of sequences in S. Equivalently, the smallest closed subset of M that contains S.',
  },
  productMetric: {
    term: 'Product metric',
    definition: 'Any of three equivalent metrics on M × N built from metrics on M and N: max, Euclidean-style, or taxicab. They all give homeomorphic spaces, so we speak of "the" product metric.',
  },

  // ────────────── Chapter 5 — Flavors of rings ──────────────
  field: {
    term: 'Field',
    symbol: 'K',
    definition: 'A nontrivial ring in which every nonzero element has a multiplicative inverse. Examples: ℚ, ℝ, ℂ, and 𝔽_p = ℤ/pℤ for prime p.',
    example: 'ℚ is a field; ℤ is not (2 has no inverse in ℤ).',
  },
  finiteField: {
    term: 'Finite field 𝔽_p',
    symbol: '\\mathbb{F}_p',
    definition: 'The field with p elements, for a prime p. Concretely it is ℤ/pℤ — the integers mod p under + and ×.',
    example: '𝔽_5 = {0,1,2,3,4} with arithmetic mod 5.',
  },
  integralDomain: {
    term: 'Integral domain',
    symbol: 'R',
    definition: 'A nontrivial commutative ring with no zero divisors: if ab = 0 then a = 0 or b = 0. Every field is an integral domain, but not vice versa.',
    example: 'ℤ is an integral domain. ℤ/6ℤ is not (2·3 = 0).',
  },
  zeroDivisor: {
    term: 'Zero divisor',
    definition: 'A nonzero element a of a ring R such that ab = 0 for some nonzero b. Integral domains are exactly the nontrivial rings with no zero divisors.',
    example: 'In ℤ/6ℤ, the element 2 is a zero divisor because 2·3 = 0.',
  },
  pid: {
    term: 'Principal ideal domain (PID)',
    symbol: '\\mathrm{PID}',
    definition: 'An integral domain in which every ideal is generated by a single element. PIDs are the rings where gcd always exists. Every Euclidean domain is a PID.',
    example: 'ℤ and k[x] (polynomials over a field k) are PIDs. ℤ[x] is not.',
  },
  primeIdeal: {
    term: 'Prime ideal',
    symbol: 'I',
    definition: 'A proper ideal I of a ring R such that whenever xy ∈ I, either x ∈ I or y ∈ I. Equivalently, R/I is an integral domain.',
    example: '(7) ⊆ ℤ is prime. (8) ⊆ ℤ is not (2·4 = 8, but 2 ∉ (8)).',
  },
  maximalIdeal: {
    term: 'Maximal ideal',
    symbol: 'I',
    definition: 'A proper ideal I of a ring R not contained in any other proper ideal. Equivalently, R/I is a field. Every maximal ideal is prime.',
    example: '(7) ⊆ ℤ is maximal. (x) ⊆ ℤ[x] is prime but not maximal.',
  },
  quotientRing: {
    term: 'Quotient ring',
    symbol: 'R/I',
    definition: 'Given a ring R and ideal I, the quotient ring R/I has elements {r + I : r ∈ R} (cosets of I) with addition and multiplication inherited from R. The canonical map r ↦ r + I is a ring homomorphism.',
  },
  fracR: {
    term: 'Field of fractions',
    symbol: '\\operatorname{Frac}(R)',
    definition: 'Given an integral domain R, the field Frac(R) consists of formal fractions a/b (b ≠ 0) with a/b = c/d iff ad = bc. The smallest field containing R as a subring.',
    example: 'Frac(ℤ) = ℚ. Frac(ℝ[x]) = ℝ(x), the rational functions.',
  },
  kOfX: {
    term: 'Field of rational functions',
    symbol: 'k(x)',
    definition: 'For a field k, the field k(x) = Frac(k[x]) consists of ratios f(x)/g(x) of polynomials with g ≠ 0, identified up to common factors.',
    example: 'ℝ(x) contains (2x)/(x²-3), 1/(x+1), and so on.',
  },
  irreducible: {
    term: 'Irreducible element',
    definition: 'A nonzero non-unit a in an integral domain such that if a = bc then b or c is a unit. Irreducibles are the "atomic" elements that cannot be factored further (up to units).',
    example: 'In ℤ, irreducibles are ±2, ±3, ±5, … In ℤ[√-5], both 2 and 1+√-5 are irreducible.',
  },
  ufd: {
    term: 'Unique factorization domain (UFD)',
    symbol: '\\mathrm{UFD}',
    definition: 'An integral domain in which every nonzero non-unit factors as a product of irreducibles, uniquely up to order and multiplication by units. Generalises the fundamental theorem of arithmetic.',
    example: 'ℤ, ℚ[x], ℤ[x], ℤ[i] are UFDs. ℤ[√-5] is not (6 has two distinct irreducible factorisations).',
  },
  euclideanDomain: {
    term: 'Euclidean domain',
    definition: 'An integral domain R with a norm function N: R\\ {0} → ℤ≥0 such that for any a, b ≠ 0 there exist q, r ∈ R with a = qb + r and r = 0 or N(r) < N(b). Supports the Euclidean algorithm. Every Euclidean domain is a PID.',
    example: 'ℤ (norm = |·|), k[x] (norm = degree), ℤ[i] (norm = a² + b²) are all Euclidean.',
  },
  euclideanNorm: {
    term: 'Euclidean norm',
    symbol: 'N \\colon R \\to \\mathbb{Z}_{\\geq 0}',
    definition: 'A function on a Euclidean domain that allows division with remainder: for any a, b with b ≠ 0, write a = qb + r with r = 0 or N(r) < N(b).',
    example: 'On ℤ[i], N(a + bi) = a² + b².',
  },

  // ────────────── Chapter 3 — Quotient groups ──────────────
  generatedS: {
    term: 'Subgroup generated by a set',
    symbol: '\\langle S \\rangle',
    definition: 'The smallest subgroup of G containing all elements of S. Concretely: all finite products of elements in S and their inverses. If ⟨S⟩ = G, S is called a generating set.',
    example: '{1} generates ℤ under addition; {r, s} generates D₂ₙ.',
  },
  generators: {
    term: 'Generators',
    definition: 'A subset S of a group G is called a set of generators if every element of G can be written as a finite product of elements of S and their inverses. S "generates" G.',
    example: '{1} generates ℤ. {r, s} with r^n = s² = 1, rs = sr⁻¹ generates D₂ₙ.',
  },
  relations: {
    term: 'Relations (in a group presentation)',
    definition: 'Equations among the generators of a group that must hold. In the presentation ⟨x | x^n = 1⟩, the relation x^n = 1 imposes that x has order dividing n.',
    example: 'D₂ₙ = ⟨r, s | r^n = s² = 1, rs = sr⁻¹⟩ has relations r^n = 1, s² = 1, rs = sr⁻¹.',
  },
  presentation: {
    term: 'Group presentation',
    symbol: '\\langle S \\mid R \\rangle',
    definition: 'A compact description of a group: ⟨generators | relations⟩. Two elements are equal iff you can get from one to the other using the relations. The same group can have many presentations.',
    example: 'ℤ/nℤ = ⟨x | x^n = 1⟩. D₂ₙ = ⟨r, s | r^n = s² = 1, rs = sr⁻¹⟩.',
  },
  freeGroup: {
    term: 'Free group',
    symbol: 'F_n',
    definition: 'The group Fₙ on n generators with no relations. Elements are reduced words in the generators and their inverses. The "largest" group on n generators — every group with n generators is a quotient of Fₙ.',
    example: 'F₁ ≅ ℤ. F₂ = ⟨a, b⟩ contains infinitely many distinct words like aba⁻¹b⁻².',
  },
  homomorphism: {
    term: 'Group homomorphism',
    symbol: '\\phi \\colon G \\to H',
    definition: 'A map φ: G → H between groups that preserves the group operation: φ(g₁g₂) = φ(g₁)φ(g₂) for all g₁, g₂ ∈ G. Isomorphisms are bijective homomorphisms.',
    example: 'Reduction mod n: ℤ → ℤ/nℤ by k ↦ k̄ is a homomorphism.',
  },
  kernel: {
    term: 'Kernel',
    symbol: '\\ker \\phi',
    definition: 'The kernel of a homomorphism φ: G → H is {g ∈ G : φ(g) = 1_H} — the elements sent to the identity. Always a subgroup of G. φ is injective iff ker φ = {1_G}.',
    example: 'The kernel of ℤ → ℤ/100ℤ is 100ℤ — the multiples of 100.',
  },
  image: {
    term: 'Image of a homomorphism',
    symbol: '\\phi(G)',
    definition: 'The image of a homomorphism φ: G → H is {φ(g) : g ∈ G} — the set of all outputs. Always a subgroup of H. φ is surjective iff φ(G) = H.',
    example: 'The image of ℤ → ℤ/100ℤ is all of ℤ/100ℤ (it is surjective).',
  },
  normalSubgroup: {
    term: 'Normal subgroup',
    symbol: 'N \\trianglelefteq G',
    definition: 'A subgroup N of G is normal if it is the kernel of some homomorphism, equivalently if gng⁻¹ ∈ N for all g ∈ G and n ∈ N. Normal subgroups are the ones you can "mod out" by. Every subgroup of an abelian group is normal.',
    example: '100ℤ ⊴ ℤ. The subgroup {1, s} ≤ D₁₂ is NOT normal.',
  },
  normalIn: {
    term: 'Normal in',
    symbol: 'N \\trianglelefteq G',
    definition: '"N is a normal subgroup of G" — N is closed under conjugation by all elements of G. Written with the triangle symbol ⊴.',
  },
  leftCoset: {
    term: 'Left coset',
    symbol: 'gH',
    definition: 'For a subgroup H ≤ G and element g ∈ G, the left coset gH = {gh : h ∈ H}. All cosets of H have the same size |H|, and they partition G into equally-sized pieces.',
    example: 'In ℤ with H = 3ℤ: the cosets are 0+3ℤ, 1+3ℤ, 2+3ℤ.',
  },
  quotientGroup: {
    term: 'Quotient group',
    symbol: 'G/N',
    definition: 'For a normal subgroup N ⊴ G, the quotient group G/N (read "G mod N") has elements = left cosets of N, with multiplication (g₁N)(g₂N) = (g₁g₂)N. Satisfies |G/N| = |G|/|N| when G is finite.',
    example: 'ℤ/nℤ is the quotient of ℤ by nℤ. D₁₀/⟨r⟩ ≅ ℤ/2ℤ.',
  },
  canonicalProjection: {
    term: 'Canonical projection',
    symbol: '\\pi \\colon G \\to G/N',
    definition: 'The surjective homomorphism π: G → G/N defined by π(g) = gN. Its kernel is exactly N. Also called the quotient map.',
  },
  conjugate: {
    term: 'Conjugate (in a group)',
    symbol: 'ghg^{-1}',
    definition: 'The conjugate of h by g is ghg⁻¹. A subgroup H is normal iff it is closed under conjugation: ghg⁻¹ ∈ H for all g ∈ G, h ∈ H.',
    example: 'In D₁₂, rsr⁻¹ = r²s ≠ s, witnessing that {1,s} is not normal.',
  },
  indexSubgroup: {
    term: 'Index of a subgroup',
    symbol: '[G:H]',
    definition: 'The number of distinct left cosets of H in G, written [G:H] = |G|/|H| (when G is finite). By Lagrange, |G| = [G:H]·|H|.',
    example: '[ℤ : 3ℤ] = 3. [D₁₀ : ⟨r⟩] = 2.',
  },
  embedding: {
    term: 'Embedding (of groups)',
    definition: 'An injective group homomorphism φ: G ↪ H. The image φ(G) is an isomorphic copy of G inside H. By the first isomorphism theorem, G ≅ φ(G).',
    example: 'S_n ↪ S_{n+1} by fixing the last point is an embedding.',
  },

  // ────────────── Chapter 4 — Rings ──────────────
  ring: {
    term: 'Ring',
    symbol: 'R',
    definition: 'A set R with two operations + and × such that (R,+) is an abelian group, × is associative with identity 1_R, and × distributes over +. In this text all rings are commutative and have a multiplicative identity.',
    example: 'ℤ, ℚ, ℝ, ℂ, ℤ/nℤ, and polynomial rings k[x] are all rings.',
  },
  commutativeRing: {
    term: 'Commutative ring',
    definition: 'A ring in which multiplication is commutative: ab = ba for all a, b. All rings in this chapter are commutative.',
  },
  zeroR: {
    term: 'Zero of a ring',
    symbol: '0_R',
    definition: 'The additive identity of the ring R — the element 0_R such that 0_R + r = r for all r. The subscript names the ring when there might be confusion.',
  },
  oneR: {
    term: 'Multiplicative identity',
    symbol: '1_R',
    definition: 'The multiplicative identity of the ring R — the element with 1_R · r = r for all r. Called "one" or "unity". Our convention: every ring has a 1_R.',
  },
  unit: {
    term: 'Unit',
    definition: 'An element u of a ring R that has a multiplicative inverse: there exists x ∈ R with ux = 1_R. The set of all units forms a group under multiplication.',
    example: 'Units of ℤ are ±1. Units of ℚ are all nonzero rationals. Units of ℤ[i] are ±1 and ±i.',
  },
  zeroRing: {
    term: 'Zero ring',
    symbol: '0',
    definition: 'The ring with a single element, where 0_R = 1_R. It is the unique ring in which the additive and multiplicative identities coincide. Not considered a field.',
  },
  polyRing: {
    term: 'Polynomial ring R[x]',
    symbol: 'R[x]',
    definition: 'The ring of polynomials with coefficients in R, in a formal variable x. Addition and multiplication are the usual polynomial operations. Pronounced "R adjoin x".',
    example: 'ℤ[x] contains 3x² - 2x + 1. ℝ[x] contains all real polynomials.',
  },
  gaussianIntegers: {
    term: 'Gaussian integers ℤ[i]',
    symbol: '\\ZZ[i]',
    definition: 'Complex numbers with integer real and imaginary parts: {a + bi : a, b ∈ ℤ}. A subring of ℂ, and isomorphic to ℤ[x]/(x²+1).',
  },
  productRing: {
    term: 'Product ring R × S',
    symbol: 'R \\times S',
    definition: 'Given rings R and S, the product ring has elements (r, s) with componentwise addition and multiplication. The identity is (1_R, 1_S).',
    example: 'ℤ/15ℤ ≅ ℤ/3ℤ × ℤ/5ℤ by the Chinese Remainder Theorem.',
  },
  ringHom: {
    term: 'Ring homomorphism',
    symbol: '\\phi \\colon R \\to S',
    definition: 'A map between rings that preserves addition, multiplication, and the multiplicative identity: φ(x+y)=φ(x)+φ(y), φ(xy)=φ(x)φ(y), φ(1_R)=1_S.',
    example: 'The reduction map ℤ → ℤ/nℤ, n ↦ n mod n, is a ring homomorphism.',
  },
  ringIso: {
    term: 'Ring isomorphism',
    symbol: 'R \\cong S',
    definition: 'A ring homomorphism that is also a bijection. Two isomorphic rings are structurally identical — same ring, different names for elements.',
  },
  ideal: {
    term: 'Ideal',
    symbol: 'I \\subseteq R',
    definition: 'A nonempty subset I of a ring R that is closed under addition and absorbs multiplication from all of R: x ∈ I and r ∈ R implies rx ∈ I. Ideals are the kernels of ring homomorphisms.',
    example: 'In ℤ, the multiples of 5 form the ideal 5ℤ = (5).',
  },
  quotientRingCh4: {
    term: 'Quotient ring R/I',
    symbol: 'R/I',
    definition: 'Given a ring R and an ideal I, the quotient ring R/I has elements {r + I : r ∈ R} (cosets of I) with the ring operations inherited from R. Think of it as R with all elements of I declared equal to zero.',
    example: 'ℤ/(5) = ℤ/5ℤ. ℤ[x]/(x-3) ≅ ℤ (evaluate at x=3).',
  },
  principalIdeal: {
    term: 'Principal ideal ⟨a⟩',
    symbol: '(a)',
    definition: 'The ideal generated by a single element a: all multiples {ra : r ∈ R}. Written (a) or ⟨a⟩. In ℤ, (n) = nℤ, the multiples of n.',
    example: '(5) = 5ℤ in ℤ. (x) in ℤ[x] is the set of polynomials with zero constant term.',
  },
  generatedIdeal: {
    term: 'Finitely generated ideal',
    symbol: '(x_1, \\dots, x_n)',
    definition: 'The ideal generated by elements x₁, …, xₙ: all elements of the form r₁x₁ + ··· + rₙxₙ with rᵢ ∈ R. The smallest ideal containing all the xᵢ.',
    example: 'In ℤ, (10, 15) = (5) = 5ℤ because gcd(10,15) = 5.',
  },
  noetherian: {
    term: 'Noetherian ring',
    definition: 'A ring in which every ideal is finitely generated. Equivalently, there is no infinite strictly ascending chain of ideals I₁ ⊊ I₂ ⊊ ···. Named after Emmy Noether.',
    example: 'ℤ, every field, every PID, and every polynomial ring ℤ[x₁,…,xₙ] are Noetherian.',
  },
  acc: {
    term: 'Ascending chain condition (ACC)',
    definition: 'The condition that there is no infinite strictly ascending chain of ideals I₁ ⊊ I₂ ⊊ I₃ ⊊ ···. Equivalent to every ideal being finitely generated. A ring with the ACC is Noetherian.',
  },

  // ────────────── Chapter 7 — Topological spaces ──────────────
  topologicalSpace: {
    term: 'Topological space',
    symbol: '(X, \\tau)',
    definition: 'A set X together with a collection τ of subsets of X — the "open sets" — such that ∅ and X are open, arbitrary unions of open sets are open, and finite intersections of open sets are open. Generalises metric spaces by keeping the notion of "open set" but throwing away the distance function.',
  },
  topology: {
    term: 'Topology',
    symbol: '\\tau',
    definition: 'The collection of open sets on a space X. Two different topologies on the same underlying set give two different topological spaces.',
  },
  openSetTop: {
    term: 'Open set (in a topological space)',
    definition: 'Any set that belongs to the topology τ. The defining notion of a topological space — no metric required.',
  },
  closedSetTop: {
    term: 'Closed set (in a topological space)',
    definition: 'A set whose complement is open. As in metric spaces: arbitrary intersections of closed sets are closed, finite unions of closed sets are closed.',
  },
  closureTop: {
    term: 'Closure (in a topological space)',
    symbol: '\\overline{S}',
    definition: 'The smallest closed set containing S. Equivalently, the intersection of all closed sets that contain S.',
  },
  clopen: {
    term: 'Clopen set',
    definition: 'A set that is simultaneously open and closed. In ℝ the only clopen sets are ∅ and ℝ; in the discrete topology every set is clopen. The clopen sets determine whether a space is connected.',
  },
  openNeighborhood: {
    term: 'Open neighborhood',
    definition: 'An open set containing a point p. The basic local-context object for talking about continuity and convergence on a topological space.',
  },
  continuousTop: {
    term: 'Continuous map (topological)',
    symbol: 'f \\colon X \\to Y',
    definition: 'A function f: X → Y between topological spaces is continuous if for every open set V ⊆ Y, the pre-image f⁻¹(V) is open in X. On metric spaces this agrees with the ε–δ definition.',
  },
  homeomorphismTop: {
    term: 'Homeomorphism (topological)',
    definition: 'A continuous bijection whose inverse is also continuous. Two homeomorphic spaces have the same topology — the same open sets up to relabelling.',
  },
  hausdorff: {
    term: 'Hausdorff space',
    definition: 'A topological space in which any two distinct points can be separated by disjoint open neighborhoods. Almost every space you meet in practice is Hausdorff; non-Hausdorff spaces are mostly curiosities.',
  },
  separationAxioms: {
    term: 'Separation axioms',
    definition: 'A hierarchy of conditions (T₀, T₁, T₂ = Hausdorff, T₃, T₄, …) that progressively guarantee distinct points or closed sets can be separated by open sets. Sharper axioms permit more analysis-style arguments.',
  },
  subspaceTopology: {
    term: 'Subspace topology',
    definition: 'Given a topological space (X, τ) and a subset S ⊆ X, the subspace topology on S has as its open sets the intersections U ∩ S for every open U ⊆ X.',
  },
  discreteSpace: {
    term: 'Discrete topology',
    definition: 'The topology on X in which every subset is open. Equivalently, the topology induced by the discrete metric. Every map out of a discrete space is automatically continuous.',
  },
  metrizable: {
    term: 'Metrizable space',
    definition: 'A topological space whose topology arises from some metric. Not every topological space is metrizable — Hausdorff is necessary but not sufficient.',
  },
  connected: {
    term: 'Connected space',
    definition: 'A space that cannot be partitioned into two nonempty disjoint open sets. Equivalently: the only clopen subsets are ∅ and the whole space.',
  },
  disconnected: {
    term: 'Disconnected space',
    definition: 'A space that admits a partition into two nonempty disjoint open sets. The negation of connected.',
  },
  pathConnected: {
    term: 'Path-connected space',
    definition: 'A space in which any two points can be joined by a continuous path γ: [0,1] → X. Path-connected implies connected, but the converse fails (topologist\'s sine curve).',
  },
  path: {
    term: 'Path',
    symbol: '\\gamma \\colon [0,1] \\to X',
    definition: 'A continuous map γ from the unit interval [0,1] into a space X. Used to define path-connectedness and the fundamental group.',
  },
  pathEndpoints: {
    term: 'Path endpoints',
    definition: 'For a path γ: [0,1] → X, the endpoints are γ(0) and γ(1). A loop is a path whose endpoints coincide.',
  },
  homotopy: {
    term: 'Homotopy',
    symbol: 'H \\colon X \\times [0,1] \\to Y',
    definition: 'A continuous deformation between two maps f, g: X → Y — a map H with H(·,0) = f and H(·,1) = g. Two maps related this way are called homotopic.',
  },
  homotopic: {
    term: 'Homotopic',
    symbol: 'f \\simeq g',
    definition: 'Two maps f, g: X → Y are homotopic if there is a homotopy between them. Being homotopic is an equivalence relation on continuous maps.',
  },
  simplyConnected: {
    term: 'Simply connected',
    definition: 'A path-connected space in which every loop is null-homotopic — can be continuously shrunk to a point. ℝⁿ is simply connected; the circle S¹ is not.',
  },
  basisTop: {
    term: 'Basis (of a topology)',
    definition: 'A collection of open sets B such that every open set is a union of members of B. The basis generates the topology. On ℝⁿ the open balls form a basis.',
  },
  topologicalProperty: {
    term: 'Topological property',
    definition: 'A property of a topological space that is preserved under homeomorphism. Compactness, connectedness, and Hausdorff-ness are topological; "having diameter ≤ 1" is not.',
  },

  // ────────────── Chapter 6 — Properties of metric spaces ──────────────
  cauchySeq: {
    term: 'Cauchy sequence',
    definition: 'A sequence (xₙ) in a metric space such that the terms get arbitrarily close to each other: for every ε > 0, d(xₘ, xₙ) < ε for all sufficiently large m and n. Every convergent sequence is Cauchy, but not vice versa in an incomplete space.',
    example: 'The decimal approximations 1, 1.4, 1.41, 1.414, … to √2 form a Cauchy sequence in ℝ. In ℚ it is Cauchy but has no limit.',
  },
  completeSpace: {
    term: 'Complete metric space',
    definition: 'A metric space in which every Cauchy sequence converges to a point of the space. ℝ and ℝⁿ are complete; ℚ and (0,1) are not.',
    example: 'ℝ is complete. The open interval (0,1) is not: the sequence 0.9, 0.99, 0.999, … is Cauchy but converges to 1 ∉ (0,1).',
  },
  totallyBounded: {
    term: 'Totally bounded',
    definition: 'A metric space that can be covered by finitely many ε-neighborhoods for any ε > 0. Implies bounded, but not vice versa. Every bounded subset of ℝⁿ is totally bounded.',
    example: '[0,1] is totally bounded. The discrete metric on ℕ is bounded but not totally bounded.',
  },
  denseSubset: {
    term: 'Dense subset',
    definition: 'A subset S of a metric space M is dense in M if every nonempty open set of M contains a point of S. Equivalently, every point of M is a limit of a sequence in S.',
    example: 'ℚ is dense in ℝ. Every metric space is dense in its completion.',
  },
  eps: {
    term: 'Epsilon (ε)',
    symbol: '\\varepsilon',
    definition: 'The Greek letter ε (epsilon), used throughout analysis as a name for an arbitrarily small positive real number. In ε-δ arguments, "for every ε > 0" means "no matter how small a positive tolerance you demand".',
  },
  contraction: {
    term: 'Contraction mapping',
    definition: 'A map T: M → M on a metric space such that d(T(p), T(q)) ≤ r·d(p,q) for some fixed r < 1 and all p, q. By the Banach fixed point theorem, every contraction on a complete metric space has a unique fixed point.',
    example: 'T(x) = x/2 on ℝ is a contraction with r = 1/2; its unique fixed point is 0.',
  },

  // ────────────── Chapter 8 — Compactness ──────────────
  subsequence: {
    term: 'Subsequence',
    definition: 'A subsequence of a sequence x₁, x₂, … is an infinite sequence xᵢ₁, xᵢ₂, … formed by keeping terms at strictly increasing index positions i₁ < i₂ < ···. It keeps infinitely many terms in their original order.',
    example: '1, 3, 5, 7, … is a subsequence of 1, 2, 3, 4, …',
  },
  sequentiallyCompact: {
    term: 'Sequentially compact',
    definition: 'A metric space M is sequentially compact if every sequence in M has a subsequence that converges to a point of M. The prototype is the closed interval [0,1].',
    example: '[0,1] is sequentially compact. ℝ is not (the sequence 1,2,3,… has no convergent subsequence). (0,1) is not (the sequence 1/2, 1/3, 1/4, … converges to 0 ∉ (0,1)).',
  },
  openCover: {
    term: 'Open cover',
    definition: 'A collection of open sets {Uα} in a topological space X such that every point of X belongs to at least one Uα. Formally, X = ⋃ Uα.',
    example: 'The collection of all open intervals (a − 1, a + 1) for a ∈ [0,1] is an open cover of [0,1].',
  },
  finiteSubcover: {
    term: 'Finite subcover',
    definition: 'A finite subcollection of an open cover that still covers the space. If {Uα} covers X, a finite subcover is a finite set {Uα₁, …, Uαₙ} ⊆ {Uα} with X = Uα₁ ∪ ··· ∪ Uαₙ.',
  },
  compact: {
    term: 'Compact space',
    definition: 'A Hausdorff topological space in which every open cover has a finite subcover. For metric spaces this is equivalent to sequential compactness. The prototype: [0,1] ⊆ ℝ.',
    example: '[0,1] and S² are compact. ℝ and (0,1) are not.',
  },
  quasicompact: {
    term: 'Quasicompact',
    definition: 'A topological space in which every open cover has a finite subcover, without requiring the Hausdorff property. Every compact space is quasicompact. The distinction matters in algebraic geometry.',
  },
  uniformlyContinuous: {
    term: 'Uniformly continuous',
    definition: 'A function f: M → N between metric spaces is uniformly continuous if for every ε > 0 there exists δ > 0 (depending only on ε, not on the point) such that d(x,y) < δ implies d(f(x),f(y)) < ε.',
    example: 'x ↦ 2x on ℝ is uniformly continuous (δ = ε/2 works everywhere). x ↦ x² on ℝ is not (large x magnifies small changes).',
  },
  lebesgueNumber: {
    term: 'Lebesgue number',
    definition: 'Given a compact metric space M and an open cover {Uα}, the Lebesgue number δ > 0 is a number such that every ball of radius δ in M is contained in some single Uα. Its existence is guaranteed by the Lebesgue number lemma.',
  },
  cofiniteTopology: {
    term: 'Cofinite topology',
    definition: 'A topology on a set X where the open sets are the empty set together with all subsets whose complement is finite. It is quasicompact but not Hausdorff when X is infinite.',
  },
  hawaiianEarring: {
    term: 'Hawaiian earring',
    definition: 'The compact subset of ℝ² consisting of circles of radius 1/n centered at (1/n, 0) for n = 1, 2, 3, …, all mutually tangent at the origin. A classical example of a compact but intricate topological space.',
  },
  productSpace: {
    term: 'Product space X × Y',
    symbol: 'X \\times Y',
    definition: 'The Cartesian product of two topological spaces X and Y, equipped with the product topology. A sequence (xₙ, yₙ) in X × Y converges if and only if both coordinate sequences converge separately.',
  },
  fIm: {
    term: 'Image of a function',
    symbol: 'f(X)',
    definition: 'The set of all output values of f: X → Y, written f(X) or f[X]. In Napkin notation this is sometimes written f^im(X). A continuous image of a compact space is compact.',
  },

  // ────────────── Chapter 14 — Bonus: Fourier analysis ──────────────
  hilbertSpace: {
    term: 'Hilbert space',
    definition: 'A complete inner product space over ℝ or ℂ. "Complete" means every Cauchy sequence converges to a point in the space. Every finite-dimensional inner product space is automatically a Hilbert space. The space L²([−π, π]) is an infinite-dimensional example.',
    example: 'ℂⁿ with the standard dot product; L²([−π, π]) with ⟨f,g⟩ = (1/2π)∫f(x)ḡ(x)dx.',
  },
  innerProduct: {
    term: 'Inner product',
    symbol: '\\langle f, g \\rangle',
    definition: 'A sesquilinear, conjugate-symmetric, positive-definite form on a complex vector space. For function spaces it is usually an average or integral of f(x)·ḡ(x). It generalises the dot product to infinite-dimensional settings.',
    example: 'On L²([−π, π]): ⟨f, g⟩ = (1/2π)∫f(x)ḡ(x)dx.',
  },
  fourierCoeff: {
    term: 'Fourier coefficient',
    symbol: '\\widehat{f}(\\xi)',
    definition: 'The coordinate of a function f in the character basis. Given an orthonormal basis (eξ) of a function space, f̂(ξ) = ⟨f, eξ⟩. The map ξ ↦ f̂(ξ) is the Fourier transform of f.',
    example: 'For f(x) = x on [−π, π], the Fourier coefficients are f̂(0) = 0 and f̂(n) = (−1)ⁿ i/n for n ≠ 0.',
  },
  circleGroup: {
    term: 'Circle group 𝕋',
    symbol: '\\mathbb{T}',
    definition: 'The additive group ℝ/ℤ of real numbers modulo 1, canonically identified with the unit circle in ℂ via the map e(θ) = exp(2πiθ). It is the natural frequency domain for continuous periodic Fourier analysis.',
  },
  character: {
    term: 'Character (Fourier)',
    definition: 'A function eξ in the orthonormal basis of a function space used for Fourier analysis. Characters are chosen to be "symmetric" — typically complex exponentials or roots of unity. The index ξ is the frequency.',
    example: 'For functions on ℤ/nℤ, the characters are eξ(x) = exp(2πiξx/n).',
  },
  physicalVariable: {
    term: 'Physical variable',
    definition: 'The input variable x ∈ Z of the function f: Z → ℂ being analysed. Distinguished from the frequency variable ξ, which indexes the characters. The name comes from physics, where x might be time or position.',
  },
  binaryFunction: {
    term: 'Boolean / binary function',
    definition: 'A function f: {±1}ⁿ → {±1} (or more generally {±1}ⁿ → ℂ). Binary Fourier analysis decomposes such functions into multilinear monomials χ_S = ∏_{s∈S} xₛ. These are the characters for the group ({±1}ⁿ, ·).',
    example: 'Majority(x₁, x₂, x₃) = sign(x₁ + x₂ + x₃) is a Boolean function on {±1}³.',
  },
  subsetFreq: {
    term: 'Subset frequency (binary Fourier)',
    definition: 'In binary Fourier analysis on {±1}ⁿ, the frequencies are subsets S ⊆ {1, …, n}. The character χ_S is the monomial ∏_{s∈S} xₛ. The Fourier coefficient f̂(S) = ⟨f, χ_S⟩ captures the "influence" of the coordinates in S on f.',
  },
  finiteAbelianGroup: {
    term: 'Finite abelian group',
    definition: 'A group that is both finite (finitely many elements) and abelian (commutative). By the fundamental theorem, every finite abelian group is isomorphic to a direct sum of cyclic groups ℤ/n₁ℤ ⊕ ··· ⊕ ℤ/nₖℤ.',
    example: 'ℤ/6ℤ, ℤ/2ℤ ⊕ ℤ/2ℤ, {±1}ⁿ (under pointwise multiplication).',
  },
  rootsOfUnityFilter: {
    term: 'Roots of unity filter',
    definition: 'An olympiad technique that extracts every k-th term of a sum by averaging with k-th roots of unity. It is exactly Fourier analysis on ℤ/kℤ: if ω = exp(2πi/k), then (1/k)∑_{j=0}^{k-1} ωʲⁿ = 1 if k | n, else 0.',
    example: 'To sum C(1000, 0) + C(1000, 3) + ··· + C(1000, 999), apply the roots of unity filter with k = 3.',
  },
  lTwo: {
    term: 'L²([−π, π])',
    symbol: 'L^2([-\\pi,\\pi])',
    definition: 'The Hilbert space of square-integrable complex-valued functions on [−π, π], with inner product ⟨f,g⟩ = (1/2π)∫f(x)ḡ(x)dx. It is infinite-dimensional and has an orthonormal basis of complex exponentials eₙ(x) = exp(inx) for n ∈ ℤ.',
  },
  pontryaginDuality: {
    term: 'Pontryagin duality',
    definition: 'A duality for locally compact abelian groups G: every such group has a dual group Ĝ (the group of continuous homomorphisms G → 𝕋), and (Ĝ)̂ ≅ G. Fourier analysis on G expands functions in terms of characters indexed by Ĝ. For finite abelian groups Ĝ ≅ G; for 𝕋, Ĝ = ℤ.',
  },
} as const satisfies Record<string, GlossaryEntry>;

export type GlossaryKey = keyof typeof glossary;

export function getEntry(key: string): GlossaryEntry | undefined {
  return (glossary as Record<string, GlossaryEntry>)[key];
}
