/**
 * Glossary of mathematical notation used across the portal.
 *
 * Each entry is keyed by a short stable identifier (used as the URL anchor
 * on /glossary and as the `key` prop of the <Term> wrapper component).
 *
 * Style:
 * - `term`: human-readable name. Plain text only — appears in the tooltip header.
 * - `symbol`: optional KaTeX source for the canonical symbol (rendered on the
 *   /glossary page; not in the tooltip).
 * - `definition`: plain text, 1–3 sentences. Appears in the tooltip and on
 *   the /glossary page. NO KaTeX in the tooltip — use unicode (ℤ, ℝ, ℂ, etc.)
 *   or describe in words.
 * - `example`: optional plain-text example, also tooltip-safe.
 *
 * Add new entries here when authoring content; reference them via
 * `<Term key="..."> ... </Term>` in MDX.
 */

export interface GlossaryEntry {
  term: string;
  symbol?: string;
  definition: string;
  example?: string;
}

export const glossary = {
  // ────────────── Number sets ──────────────
  ZZ: {
    term: 'Integers',
    symbol: '\\ZZ',
    definition: 'The integers: …, −2, −1, 0, 1, 2, …. Written with the blackboard-bold ℤ.',
  },
  NN: {
    term: 'Natural numbers',
    symbol: '\\NN',
    definition: 'The natural numbers. In Napkin this includes 0: 0, 1, 2, 3, …',
  },
  QQ: {
    term: 'Rational numbers',
    symbol: '\\QQ',
    definition: 'The rationals: every fraction a/b where a and b are integers and b ≠ 0.',
  },
  RR: {
    term: 'Real numbers',
    symbol: '\\RR',
    definition: 'The real numbers: every point on the number line, including irrationals like √2 and π.',
  },
  CC: {
    term: 'Complex numbers',
    symbol: '\\CC',
    definition: 'The complex numbers, of the form a + bi where a, b are real and i² = −1.',
  },
  Qtimes: {
    term: 'Non-zero rationals',
    symbol: '\\QQ^\\times',
    definition: 'The rationals with 0 removed. The superscript × means "drop the elements that have no multiplicative inverse" — for ℚ that means just dropping 0.',
  },

  // ────────────── Group structure ──────────────
  identity: {
    term: 'Group identity',
    symbol: '1_G',
    definition: 'The identity element of a group G — the element that, combined with any g, gives back g. The subscript names which group\'s identity it is. Sometimes written 0_G when the operation is additive.',
  },
  inverse: {
    term: 'Group inverse',
    symbol: 'g^{-1}',
    definition: 'The inverse of g: the unique element that combines with g to give the identity. The −1 superscript is just notation; for (ℚ×, ·) it really is 1/x, but for a general group it just means "the inverse".',
  },
  power: {
    term: 'Group power',
    symbol: 'g^n',
    definition: 'g combined with itself n times under the group operation. For n = 0 this is the identity; for negative n it means (g⁻¹)^|n|.',
  },
  star: {
    term: 'Generic group operation',
    symbol: '\\star',
    definition: 'A placeholder for "any binary operation" — used instead of + or · to emphasise the operation could be anything.',
  },
  groupOrder: {
    term: 'Order of a group',
    symbol: '|G|',
    definition: 'The number of elements in the group G. May be infinite, e.g. |ℤ| = ∞.',
  },
  elementOrder: {
    term: 'Order of an element',
    symbol: '\\ord g',
    definition: 'The smallest positive integer n with g^n equal to the identity. ∞ if no such n exists.',
  },
  generated: {
    term: 'Subgroup generated by an element',
    symbol: '\\langle x \\rangle',
    definition: 'The smallest subgroup containing x — namely all integer powers of x: …, x⁻², x⁻¹, 1, x, x², …',
  },
  isomorphic: {
    term: 'Isomorphic',
    symbol: '\\cong',
    definition: '"Is isomorphic to" — there exists a structure-preserving bijection between two groups. Treat them as the same group with different names for elements.',
  },

  // ────────────── Specific groups ──────────────
  Zc: {
    term: 'Cyclic group of order n',
    symbol: '\\Zc{n}',
    definition: 'Clock arithmetic: the integers mod n, written ℤ/nℤ. Elements are {0, 1, …, n−1}; addition wraps around at n. ℤ/12ℤ is a 12-hour clock.',
  },
  Zm: {
    term: 'Multiplicative group mod p',
    symbol: '\\Zm{p}',
    definition: 'For a prime p: the non-zero residues {1, 2, …, p−1} under multiplication mod p. The primality is what guarantees every element has a multiplicative inverse.',
  },
  Sn: {
    term: 'Symmetric group',
    symbol: 'S_n',
    definition: 'All permutations (re-orderings) of {1, 2, …, n} under composition. Has n! elements; non-abelian for n ≥ 3.',
  },
  Dn: {
    term: 'Dihedral group',
    symbol: 'D_{2n}',
    definition: 'Symmetries of a regular n-gon — n rotations and n reflections, 2n elements total. Non-abelian for n ≥ 3.',
  },
  GLn: {
    term: 'General linear group',
    symbol: '\\GL_n(\\RR)',
    definition: 'Invertible n×n real matrices, under matrix multiplication. The "general linear group of degree n over ℝ".',
  },
  SLn: {
    term: 'Special linear group',
    symbol: '\\SL_n(\\RR)',
    definition: 'n×n real matrices with determinant 1, under matrix multiplication. A subgroup of GLₙ(ℝ).',
  },
  Q8: {
    term: 'Quaternion group',
    symbol: 'Q_8',
    definition: 'A non-abelian group of order 8, with elements ±1, ±i, ±j, ±k satisfying i² = j² = k² = ijk = −1.',
  },
  Mat: {
    term: 'Set of n×n matrices',
    symbol: '\\Mat_{n \\times n}(\\RR)',
    definition: 'All n×n real matrices (not just invertible ones). Used as a non-example: not a group under multiplication because the zero matrix has no inverse.',
  },
  S1: {
    term: 'Complex unit circle',
    symbol: 'S^1',
    definition: 'The complex numbers of absolute value 1: {z ∈ ℂ : |z| = 1}. Under multiplication this is a group.',
  },
  trivial: {
    term: 'Trivial group',
    symbol: '\\{1\\}',
    definition: 'The group with a single element — just the identity. Often written {1} or {1_G}.',
  },

  // ────────────── Mod-arithmetic notation ──────────────
  pmod: {
    term: 'Modulo',
    symbol: '\\pmod{n}',
    definition: '"Modulo n" — equality up to multiples of n. e.g. 7 ≡ 1 (mod 3) means 7 and 1 differ by a multiple of 3.',
  },
  bar: {
    term: 'Residue class',
    symbol: '\\overline{a}',
    definition: 'The residue class of a mod n: a together with everything that differs from a by a multiple of n. So in ℤ/3ℤ, ̄2 = {…, −1, 2, 5, 8, …}.',
  },
  divides: {
    term: 'Divides',
    symbol: 'a \\mid b',
    definition: '"a divides b" — there is an integer k with b = ka. So 3 ∣ 12 (since 12 = 3·4) but 3 ∤ 7.',
  },
  congruent: {
    term: 'Congruent',
    symbol: '\\equiv',
    definition: '"Is congruent to" — usually paired with (mod n). a ≡ b (mod n) means n divides (a − b).',
  },

  // ────────────── Set / function notation ──────────────
  in: {
    term: 'Element of',
    symbol: '\\in',
    definition: '"Is an element of". x ∈ S means x is in the set S.',
  },
  setbuilderBar: {
    term: 'Such that (in set-builder)',
    symbol: '\\{ x \\in S \\mid P(x) \\}',
    definition: 'Inside set-builder braces, the | (or :) is read "such that". {z ∈ ℂ ∣ |z|=1} is "the z in ℂ such that |z|=1".',
  },
  to: {
    term: 'Function arrow',
    symbol: 'f \\colon A \\to B',
    definition: 'f is a function from A to B. A is the domain, B the codomain.',
  },
  mapsto: {
    term: 'Maps to',
    symbol: 'x \\mapsto y',
    definition: 'Specifies what a function does to inputs. f(x) = x² can be written x ↦ x².',
  },
  subset: {
    term: 'Subset',
    symbol: '\\subseteq',
    definition: '"Is a subset of" (allows equality). For strict-subset use ⊊.',
  },
  emptyset: {
    term: 'Empty set',
    symbol: '\\varnothing',
    definition: 'The set with no elements. Sometimes written ∅ or {}.',
  },

  // ────────────── Metric topology (Chapter 2) ──────────────
  metricSpace: {
    term: 'Metric space',
    symbol: '(M, d)',
    definition: 'A pair consisting of a set M and a distance function d that satisfies symmetry, positive-definiteness, and the triangle inequality.',
  },
  metric: {
    term: 'Metric',
    symbol: 'd \\colon M \\times M \\to \\RR_{\\ge 0}',
    definition: 'The distance function on a metric space. Takes two points and returns a non-negative real number — their "distance".',
  },
  triangleIneq: {
    term: 'Triangle inequality',
    symbol: 'd(x,z) \\le d(x,y) + d(y,z)',
    definition: 'A metric axiom: going via a third point z is never shorter than going directly from x to y.',
  },
  positiveDef: {
    term: 'Positive-definite',
    definition: 'For a metric d: d(x,y) ≥ 0, with equality if and only if x = y. (Zero distance ⇒ same point.)',
  },
  euclideanMetric: {
    term: 'Euclidean metric',
    symbol: 'd(x, y) = \\sqrt{\\sum (x_i - y_i)^2}',
    definition: 'The standard "straight-line distance" on ℝⁿ — square root of the sum of squared coordinate differences.',
  },
  taxicabMetric: {
    term: 'Taxicab metric',
    symbol: 'd(x, y) = \\sum |x_i - y_i|',
    definition: 'A metric on ℝⁿ: the sum of absolute coordinate differences. Equals the path length you\'d travel on a city grid.',
  },
  discreteMetric: {
    term: 'Discrete metric',
    definition: 'A metric on any set: d(x,y) = 0 if x = y, otherwise d(x,y) = 1. Every two distinct points are exactly 1 apart.',
  },
  RRn: {
    term: 'n-dimensional Euclidean space',
    symbol: '\\RR^n',
    definition: 'The set of ordered n-tuples of real numbers, with the Euclidean metric.',
  },
  openBall: {
    term: 'Open unit ball',
    symbol: 'B^n',
    definition: 'The set of points (x₁, …, xₙ) in ℝⁿ with x₁² + ⋯ + xₙ² < 1. Strict inequality — boundary is excluded.',
  },
  unitSphere: {
    term: 'Unit sphere',
    symbol: 'S^{n-1}',
    definition: 'The set of points in ℝⁿ at distance exactly 1 from the origin. The superscript n−1 is the intrinsic dimension (the surface of an n-ball).',
  },
  rNeighborhood: {
    term: 'r-neighborhood',
    symbol: 'M_r(p)',
    definition: 'The set of all points within distance r of p in a metric space. Also called an open ball of radius r centred at p.',
  },
  convergence: {
    term: 'Convergence',
    definition: 'A sequence (xₙ) converges to x if for every ε > 0, all but finitely many terms are within ε of x. The choice of metric matters!',
  },
  continuous: {
    term: 'Continuous map',
    definition: 'A function f between metric spaces is continuous at p if small changes in input give small changes in output — formally, the ε–δ definition.',
  },
  homeomorphism: {
    term: 'Homeomorphism',
    definition: 'A continuous bijection whose inverse is also continuous. Two spaces with one between them are "topologically the same".',
  },
  openSet: {
    term: 'Open set',
    definition: 'A subset U of a metric space such that every point of U has a (small enough) neighborhood entirely inside U.',
  },
  closedSet: {
    term: 'Closed set',
    definition: 'A subset whose complement is open. Equivalently, a set containing all its limit points.',
  },
  limitPoint: {
    term: 'Limit point',
    symbol: '\\lim S',
    definition: 'A point p of a metric space M is a limit point of S ⊆ M if some sequence in S converges to p. The set of all such p is written lim S.',
  },
  closure: {
    term: 'Closure',
    symbol: '\\overline{S}',
    definition: 'The closure of S in M: the set of all limits of sequences in S. Equivalently, the smallest closed subset of M that contains S.',
  },
  productMetric: {
    term: 'Product metric',
    definition: 'Any of three equivalent metrics on M × N built from metrics on M and N: max, Euclidean-style, or taxicab. They all give homeomorphic spaces, so we speak of "the" product metric.',
  },

  // ────────────── Chapter 5 — Flavors of rings ──────────────
  field: {
    term: 'Field',
    symbol: 'K',
    definition: 'A nontrivial ring in which every nonzero element has a multiplicative inverse. Examples: ℚ, ℝ, ℂ, and 𝔽_p = ℤ/pℤ for prime p.',
    example: 'ℚ is a field; ℤ is not (2 has no inverse in ℤ).',
  },
  finiteField: {
    term: 'Finite field 𝔽_p',
    symbol: '\\mathbb{F}_p',
    definition: 'The field with p elements, for a prime p. Concretely it is ℤ/pℤ — the integers mod p under + and ×.',
    example: '𝔽_5 = {0,1,2,3,4} with arithmetic mod 5.',
  },
  integralDomain: {
    term: 'Integral domain',
    symbol: 'R',
    definition: 'A nontrivial commutative ring with no zero divisors: if ab = 0 then a = 0 or b = 0. Every field is an integral domain, but not vice versa.',
    example: 'ℤ is an integral domain. ℤ/6ℤ is not (2·3 = 0).',
  },
  zeroDivisor: {
    term: 'Zero divisor',
    definition: 'A nonzero element a of a ring R such that ab = 0 for some nonzero b. Integral domains are exactly the nontrivial rings with no zero divisors.',
    example: 'In ℤ/6ℤ, the element 2 is a zero divisor because 2·3 = 0.',
  },
  pid: {
    term: 'Principal ideal domain (PID)',
    symbol: '\\mathrm{PID}',
    definition: 'An integral domain in which every ideal is generated by a single element. PIDs are the rings where gcd always exists. Every Euclidean domain is a PID.',
    example: 'ℤ and k[x] (polynomials over a field k) are PIDs. ℤ[x] is not.',
  },
  primeIdeal: {
    term: 'Prime ideal',
    symbol: 'I',
    definition: 'A proper ideal I of a ring R such that whenever xy ∈ I, either x ∈ I or y ∈ I. Equivalently, R/I is an integral domain.',
    example: '(7) ⊆ ℤ is prime. (8) ⊆ ℤ is not (2·4 = 8, but 2 ∉ (8)).',
  },
  maximalIdeal: {
    term: 'Maximal ideal',
    symbol: 'I',
    definition: 'A proper ideal I of a ring R not contained in any other proper ideal. Equivalently, R/I is a field. Every maximal ideal is prime.',
    example: '(7) ⊆ ℤ is maximal. (x) ⊆ ℤ[x] is prime but not maximal.',
  },
  quotientRing: {
    term: 'Quotient ring',
    symbol: 'R/I',
    definition: 'Given a ring R and ideal I, the quotient ring R/I has elements {r + I : r ∈ R} (cosets of I) with addition and multiplication inherited from R. The canonical map r ↦ r + I is a ring homomorphism.',
  },
  fracR: {
    term: 'Field of fractions',
    symbol: '\\operatorname{Frac}(R)',
    definition: 'Given an integral domain R, the field Frac(R) consists of formal fractions a/b (b ≠ 0) with a/b = c/d iff ad = bc. The smallest field containing R as a subring.',
    example: 'Frac(ℤ) = ℚ. Frac(ℝ[x]) = ℝ(x), the rational functions.',
  },
  kOfX: {
    term: 'Field of rational functions',
    symbol: 'k(x)',
    definition: 'For a field k, the field k(x) = Frac(k[x]) consists of ratios f(x)/g(x) of polynomials with g ≠ 0, identified up to common factors.',
    example: 'ℝ(x) contains (2x)/(x²-3), 1/(x+1), and so on.',
  },
  irreducible: {
    term: 'Irreducible element',
    definition: 'A nonzero non-unit a in an integral domain such that if a = bc then b or c is a unit. Irreducibles are the "atomic" elements that cannot be factored further (up to units).',
    example: 'In ℤ, irreducibles are ±2, ±3, ±5, … In ℤ[√-5], both 2 and 1+√-5 are irreducible.',
  },
  ufd: {
    term: 'Unique factorization domain (UFD)',
    symbol: '\\mathrm{UFD}',
    definition: 'An integral domain in which every nonzero non-unit factors as a product of irreducibles, uniquely up to order and multiplication by units. Generalises the fundamental theorem of arithmetic.',
    example: 'ℤ, ℚ[x], ℤ[x], ℤ[i] are UFDs. ℤ[√-5] is not (6 has two distinct irreducible factorisations).',
  },
  euclideanDomain: {
    term: 'Euclidean domain',
    definition: 'An integral domain R with a norm function N: R\\ {0} → ℤ≥0 such that for any a, b ≠ 0 there exist q, r ∈ R with a = qb + r and r = 0 or N(r) < N(b). Supports the Euclidean algorithm. Every Euclidean domain is a PID.',
    example: 'ℤ (norm = |·|), k[x] (norm = degree), ℤ[i] (norm = a² + b²) are all Euclidean.',
  },
  euclideanNorm: {
    term: 'Euclidean norm',
    symbol: 'N \\colon R \\to \\mathbb{Z}_{\\geq 0}',
    definition: 'A function on a Euclidean domain that allows division with remainder: for any a, b with b ≠ 0, write a = qb + r with r = 0 or N(r) < N(b).',
    example: 'On ℤ[i], N(a + bi) = a² + b².',
  },

  // ────────────── Chapter 4 — Rings ──────────────
  ring: {
    term: 'Ring',
    symbol: 'R',
    definition: 'A set R with two operations + and × such that (R,+) is an abelian group, × is associative with identity 1_R, and × distributes over +. In this text all rings are commutative and have a multiplicative identity.',
    example: 'ℤ, ℚ, ℝ, ℂ, ℤ/nℤ, and polynomial rings k[x] are all rings.',
  },
  commutativeRing: {
    term: 'Commutative ring',
    definition: 'A ring in which multiplication is commutative: ab = ba for all a, b. All rings in this chapter are commutative.',
  },
  zeroR: {
    term: 'Zero of a ring',
    symbol: '0_R',
    definition: 'The additive identity of the ring R — the element 0_R such that 0_R + r = r for all r. The subscript names the ring when there might be confusion.',
  },
  oneR: {
    term: 'Multiplicative identity',
    symbol: '1_R',
    definition: 'The multiplicative identity of the ring R — the element with 1_R · r = r for all r. Called "one" or "unity". Our convention: every ring has a 1_R.',
  },
  unit: {
    term: 'Unit',
    definition: 'An element u of a ring R that has a multiplicative inverse: there exists x ∈ R with ux = 1_R. The set of all units forms a group under multiplication.',
    example: 'Units of ℤ are ±1. Units of ℚ are all nonzero rationals. Units of ℤ[i] are ±1 and ±i.',
  },
  zeroRing: {
    term: 'Zero ring',
    symbol: '0',
    definition: 'The ring with a single element, where 0_R = 1_R. It is the unique ring in which the additive and multiplicative identities coincide. Not considered a field.',
  },
  polyRing: {
    term: 'Polynomial ring R[x]',
    symbol: 'R[x]',
    definition: 'The ring of polynomials with coefficients in R, in a formal variable x. Addition and multiplication are the usual polynomial operations. Pronounced "R adjoin x".',
    example: 'ℤ[x] contains 3x² - 2x + 1. ℝ[x] contains all real polynomials.',
  },
  gaussianIntegers: {
    term: 'Gaussian integers ℤ[i]',
    symbol: '\\ZZ[i]',
    definition: 'Complex numbers with integer real and imaginary parts: {a + bi : a, b ∈ ℤ}. A subring of ℂ, and isomorphic to ℤ[x]/(x²+1).',
  },
  productRing: {
    term: 'Product ring R × S',
    symbol: 'R \\times S',
    definition: 'Given rings R and S, the product ring has elements (r, s) with componentwise addition and multiplication. The identity is (1_R, 1_S).',
    example: 'ℤ/15ℤ ≅ ℤ/3ℤ × ℤ/5ℤ by the Chinese Remainder Theorem.',
  },
  ringHom: {
    term: 'Ring homomorphism',
    symbol: '\\phi \\colon R \\to S',
    definition: 'A map between rings that preserves addition, multiplication, and the multiplicative identity: φ(x+y)=φ(x)+φ(y), φ(xy)=φ(x)φ(y), φ(1_R)=1_S.',
    example: 'The reduction map ℤ → ℤ/nℤ, n ↦ n mod n, is a ring homomorphism.',
  },
  ringIso: {
    term: 'Ring isomorphism',
    symbol: 'R \\cong S',
    definition: 'A ring homomorphism that is also a bijection. Two isomorphic rings are structurally identical — same ring, different names for elements.',
  },
  ideal: {
    term: 'Ideal',
    symbol: 'I \\subseteq R',
    definition: 'A nonempty subset I of a ring R that is closed under addition and absorbs multiplication from all of R: x ∈ I and r ∈ R implies rx ∈ I. Ideals are the kernels of ring homomorphisms.',
    example: 'In ℤ, the multiples of 5 form the ideal 5ℤ = (5).',
  },
  quotientRingCh4: {
    term: 'Quotient ring R/I',
    symbol: 'R/I',
    definition: 'Given a ring R and an ideal I, the quotient ring R/I has elements {r + I : r ∈ R} (cosets of I) with the ring operations inherited from R. Think of it as R with all elements of I declared equal to zero.',
    example: 'ℤ/(5) = ℤ/5ℤ. ℤ[x]/(x-3) ≅ ℤ (evaluate at x=3).',
  },
  principalIdeal: {
    term: 'Principal ideal ⟨a⟩',
    symbol: '(a)',
    definition: 'The ideal generated by a single element a: all multiples {ra : r ∈ R}. Written (a) or ⟨a⟩. In ℤ, (n) = nℤ, the multiples of n.',
    example: '(5) = 5ℤ in ℤ. (x) in ℤ[x] is the set of polynomials with zero constant term.',
  },
  generatedIdeal: {
    term: 'Finitely generated ideal',
    symbol: '(x_1, \\dots, x_n)',
    definition: 'The ideal generated by elements x₁, …, xₙ: all elements of the form r₁x₁ + ··· + rₙxₙ with rᵢ ∈ R. The smallest ideal containing all the xᵢ.',
    example: 'In ℤ, (10, 15) = (5) = 5ℤ because gcd(10,15) = 5.',
  },
  noetherian: {
    term: 'Noetherian ring',
    definition: 'A ring in which every ideal is finitely generated. Equivalently, there is no infinite strictly ascending chain of ideals I₁ ⊊ I₂ ⊊ ···. Named after Emmy Noether.',
    example: 'ℤ, every field, every PID, and every polynomial ring ℤ[x₁,…,xₙ] are Noetherian.',
  },
  acc: {
    term: 'Ascending chain condition (ACC)',
    definition: 'The condition that there is no infinite strictly ascending chain of ideals I₁ ⊊ I₂ ⊊ I₃ ⊊ ···. Equivalent to every ideal being finitely generated. A ring with the ACC is Noetherian.',
  },
} as const satisfies Record<string, GlossaryEntry>;

export type GlossaryKey = keyof typeof glossary;

export function getEntry(key: string): GlossaryEntry | undefined {
  return (glossary as Record<string, GlossaryEntry>)[key];
}
