import { test, expect } from '@playwright/test';

const BASE = '/part-1-starting-out/01-groups/05-subgroups';

const SLIDES: Array<{ url: string; heading: RegExp | string }> = [
  { url: `${BASE}/01-definition`, heading: /defining a subgroup/i },
  { url: `${BASE}/02-examples`, heading: /examples of subgroups/i },
  { url: `${BASE}/03-subgroup-generated`, heading: /subgroup generated by an element/i },
  { url: `${BASE}/04-cyclic-subgroup-exercise`, heading: /cyclic subgroups, finite and infinite/i },
  { url: `${BASE}/05-non-examples`, heading: /non-examples of subgroups/i },
];

test.beforeEach(async ({ page }) => {
  await page.goto('/');
  await page.evaluate(() => window.localStorage.clear());
});

test.describe('Groups · Subgroups section — slide URLs load', () => {
  for (const slide of SLIDES) {
    test(`loads ${slide.url} and shows heading`, async ({ page }) => {
      const resp = await page.goto(slide.url);
      expect(resp?.status()).toBe(200);
      await expect(page.getByRole('heading', { level: 1, name: slide.heading })).toBeVisible();
    });
  }
});

test.describe('Groups · Subgroups section — KaTeX renders', () => {
  test('subgroup-generated slide renders display math (definition of <x>)', async ({ page }) => {
    await page.goto(`${BASE}/03-subgroup-generated`);
    await expect(page.locator('.katex-display').first()).toBeVisible();
  });
});

test.describe('Groups · Subgroups — NumericInput flow (size of <x> when ord x = 7)', () => {
  const SLIDE = `${BASE}/03-subgroup-generated`;
  const NUM_KEY = `napkin:exercise:${SLIDE}#grp-sub-num-cyclic-size-7`;

  test('wrong then correct, persists across reload', async ({ page }) => {
    await page.goto(SLIDE);

    const input = page.getByPlaceholder('a number').first();
    await input.fill('6');
    await page.getByRole('button', { name: /^check$/i }).first().click();
    await expect(page.getByText(/not quite/i).first()).toBeVisible();

    await input.fill('7');
    await page.getByRole('button', { name: /^check$/i }).first().click();
    await expect(page.getByText('Correct.').first()).toBeVisible();

    expect(await page.evaluate((k) => window.localStorage.getItem(k), NUM_KEY)).toContain(
      '"outcome":"correct"',
    );

    await page.reload();
    await expect(page.getByText('Correct.').first()).toBeVisible();
    await expect(input).toHaveValue('7');
  });
});

test.describe('Groups · Subgroups — MCQ flow (which is NOT a subgroup of Z)', () => {
  const SLIDE = `${BASE}/05-non-examples`;
  const MCQ_KEY = `napkin:exercise:${SLIDE}#grp-sub-mcq-not-a-subgroup`;

  test('correct answer is recorded and persists across reload', async ({ page }) => {
    await page.goto(SLIDE);
    await page.getByRole('button', { name: /perfect squares/i }).click();

    await expect(page.getByText('Why:').first()).toBeVisible();
    expect(await page.evaluate((k) => window.localStorage.getItem(k), MCQ_KEY)).toContain(
      '"outcome":"correct"',
    );

    await page.reload();
    await expect(page.getByText('Why:').first()).toBeVisible();
  });

  test('wrong answer is recorded as incorrect', async ({ page }) => {
    await page.goto(SLIDE);
    await page.getByRole('button', { name: /the even integers 2z/i }).click();

    await expect(page.getByText('Why:').first()).toBeVisible();
    expect(await page.evaluate((k) => window.localStorage.getItem(k), MCQ_KEY)).toContain(
      '"outcome":"incorrect"',
    );
  });
});

test.describe('Groups · Subgroups — ProofReveal flow (cyclic subgroup shape)', () => {
  const SLIDE = `${BASE}/04-cyclic-subgroup-exercise`;
  const PROOF_KEY = `napkin:exercise:${SLIDE}#grp-sub-proof-cyclic-shape`;

  test('reveal shows solution and persists across reload', async ({ page }) => {
    await page.goto(SLIDE);

    const article = page.getByRole('article');
    await expect(article.getByText(/cyclic group of order 2015/i)).toBeHidden();

    await page.getByRole('button', { name: /reveal solution/i }).click();
    await expect(article.getByText(/cyclic group of order 2015/i)).toBeVisible();

    expect(await page.evaluate((k) => window.localStorage.getItem(k), PROOF_KEY)).toContain(
      '"outcome":"revealed"',
    );

    await page.reload();
    await expect(article.getByText(/cyclic group of order 2015/i)).toBeVisible();
  });
});
