import { test, expect } from '@playwright/test';

const BASE = '/part-14-algebraic-nt-i-rings-of-integers/02-the-ring-of-integers';

test.beforeEach(async ({ page }) => {
  await page.goto('/');
  await page.evaluate(() => window.localStorage.clear());
});

// ── KaTeX renders ─────────────────────────────────────────────────────────────
test.describe('The ring of integers — KaTeX renders', () => {
  test('norm definition slide renders KaTeX math', async ({ page }) => {
    await page.goto(`${BASE}/01-norms-and-traces/04-norm-definition`);
    await expect(page.locator('.katex').first()).toBeVisible();
  });
});

// ── MCQ flow ──────────────────────────────────────────────────────────────────
test.describe('The ring of integers — MCQ flow (correction factor k)', () => {
  const SLIDE = `${BASE}/01-norms-and-traces/04-norm-definition`;
  const MCQ_KEY = `napkin:exercise:${SLIDE}#an54-s1-mcq-k-value`;

  test('correct answer persists across reload', async ({ page }) => {
    await page.goto(SLIDE);
    await page.getByRole('button', { name: /k = 2 \(since deg K = 2 and deg 3 = 1, so k = 2\/1 = 2\)/i }).click();
    await expect(page.getByText('Why:').first()).toBeVisible();
    expect(await page.evaluate((k) => window.localStorage.getItem(k), MCQ_KEY)).toContain(
      '"outcome":"correct"',
    );
    await page.reload();
    await expect(page.getByText('Why:').first()).toBeVisible();
  });

  test('wrong answer is recorded as incorrect', async ({ page }) => {
    await page.goto(SLIDE);
    await page.getByRole('button', { name: /k = 1 \(since 3 has degree 1 in ℚ\(i\)\)/i }).click();
    await expect(page.getByText('Why:').first()).toBeVisible();
    expect(await page.evaluate((k) => window.localStorage.getItem(k), MCQ_KEY)).toContain(
      '"outcome":"incorrect"',
    );
  });
});

// ── NumericInput flow ─────────────────────────────────────────────────────────
test.describe('The ring of integers — NumericInput flow (norm in ℚ(√2))', () => {
  const SLIDE = `${BASE}/01-norms-and-traces/05-quadratic-example`;
  const NUM_KEY = `napkin:exercise:${SLIDE}#an54-s1-num-norm-sqrt2`;

  test('wrong then correct, persists across reload', async ({ page }) => {
    await page.goto(SLIDE);

    const input = page.getByPlaceholder('a number').first();
    await input.fill('9');
    await page.getByRole('button', { name: /^check$/i }).first().click();
    await expect(page.getByText(/not quite/i).first()).toBeVisible();

    await input.fill('7');
    await page.getByRole('button', { name: /^check$/i }).first().click();
    await expect(page.getByText('Correct.').first()).toBeVisible();

    expect(await page.evaluate((k) => window.localStorage.getItem(k), NUM_KEY)).toContain(
      '"outcome":"correct"',
    );

    await page.reload();
    await expect(page.getByText('Correct.').first()).toBeVisible();
    await expect(input).toHaveValue('7');
  });
});

// ── ProofReveal flow ──────────────────────────────────────────────────────────
test.describe('The ring of integers — ProofReveal flow (𝒪_K is a ring)', () => {
  const SLIDE = `${BASE}/02-the-ring-of-integers/07-ok-is-a-ring`;
  const PROOF_KEY = `napkin:exercise:${SLIDE}#an54-s2-proof-ok-ring`;

  test('reveal shows solution and persists across reload', async ({ page }) => {
    await page.goto(SLIDE);

    const article = page.getByRole('article');
    await expect(article.getByText(/finitely generated by mn elements/i)).toBeHidden();

    await page.getByRole('button', { name: /reveal solution/i }).click();
    await expect(article.getByText(/finitely generated by mn elements/i)).toBeVisible();

    expect(await page.evaluate((k) => window.localStorage.getItem(k), PROOF_KEY)).toContain(
      '"outcome":"revealed"',
    );

    await page.reload();
    await expect(article.getByText(/finitely generated by mn elements/i)).toBeVisible();
  });
});

// ── Problem flow ──────────────────────────────────────────────────────────────
test.describe('The ring of integers — Problem flow (units and norm)', () => {
  const SLIDE = `${BASE}/04-problems/01-units-and-fractions`;
  const PROB_KEY = `napkin:exercise:${SLIDE}#an54-prob-units-norm`;

  test('showing solution writes to localStorage', async ({ page }) => {
    await page.goto(SLIDE);

    const article = page.getByRole('article');
    // "by multiplicativity" only appears inside the solution text
    await expect(article.getByText(/by multiplicativity/i)).toBeHidden();

    await page.getByRole('button', { name: /show solution/i }).first().click();
    await expect(article.getByText(/by multiplicativity/i)).toBeVisible();

    const stored = await page.evaluate((k) => window.localStorage.getItem(k), PROB_KEY);
    expect(stored).not.toBeNull();
  });
});
