import { test, expect } from '@playwright/test';

const BASE = '/part-15-algebraic-nt-ii-galois-and-ramification-theory/04-the-frobenius-element';

test.beforeEach(async ({ page }) => {
  await page.goto('/');
  await page.evaluate(() => window.localStorage.clear());
});

// ── KaTeX renders ─────────────────────────────────────────────────────────────
test.describe('Frobenius element — KaTeX renders', () => {
  test('setting-the-stage slide renders KaTeX math', async ({ page }) => {
    await page.goto(`${BASE}/01-frobenius-elements/01-setting-the-stage`);
    await expect(page.locator('.katex').first()).toBeVisible();
  });
});

// ── MCQ flow ──────────────────────────────────────────────────────────────────
test.describe('Frobenius element — MCQ flow (Frobenius at p = 13 in ℤ[i])', () => {
  const SLIDE = `${BASE}/01-frobenius-elements/03-example-gaussian-integers`;
  const MCQ_KEY = `napkin:exercise:${SLIDE}#frob-elem-mcq-gaussian-13`;

  test('correct answer persists across reload', async ({ page }) => {
    await page.goto(SLIDE);
    await page.getByRole('button', { name: 'The identity', exact: true }).click();
    await expect(page.getByText('Why:').first()).toBeVisible();
    expect(await page.evaluate((k) => window.localStorage.getItem(k), MCQ_KEY)).toContain(
      '"outcome":"correct"',
    );
    await page.reload();
    await expect(page.getByText('Why:').first()).toBeVisible();
  });

  test('wrong answer is recorded as incorrect', async ({ page }) => {
    await page.goto(SLIDE);
    await page.getByRole('button', { name: 'Complex conjugation', exact: true }).click();
    await expect(page.getByText('Why:').first()).toBeVisible();
    expect(await page.evaluate((k) => window.localStorage.getItem(k), MCQ_KEY)).toContain(
      '"outcome":"incorrect"',
    );
  });
});

// ── NumericInput flow ─────────────────────────────────────────────────────────
test.describe('Frobenius element — NumericInput flow (Chebotarev density)', () => {
  const SLIDE = `${BASE}/03-chebotarev-density-theorem/03-throwing-darts-at-g`;
  const NUM_KEY = `napkin:exercise:${SLIDE}#frob-cheb-num-density`;

  test('wrong then correct, persists across reload', async ({ page }) => {
    await page.goto(SLIDE);

    const input = page.getByPlaceholder('a number').first();
    await input.fill('1/4');
    await page.getByRole('button', { name: /^check$/i }).first().click();
    await expect(page.getByText(/not quite/i).first()).toBeVisible();

    await input.fill('1/6');
    await page.getByRole('button', { name: /^check$/i }).first().click();
    await expect(page.getByText('Correct.').first()).toBeVisible();

    expect(await page.evaluate((k) => window.localStorage.getItem(k), NUM_KEY)).toContain(
      '"outcome":"correct"',
    );

    await page.reload();
    await expect(page.getByText('Correct.').first()).toBeVisible();
    await expect(input).toHaveValue('1/6');
  });
});

// ── ProofReveal flow ──────────────────────────────────────────────────────────
test.describe('Frobenius element — ProofReveal flow (order of the Frobenius element)', () => {
  const SLIDE = `${BASE}/01-frobenius-elements/05-order-of-the-frobenius-element`;
  const PROOF_KEY = `napkin:exercise:${SLIDE}#frob-elem-proof-order-lemma`;

  test('reveal shows solution and persists across reload', async ({ page }) => {
    await page.goto(SLIDE);

    const article = page.getByRole('article');
    await expect(article.getByText(/cyclic of order f, generated by T/i)).toBeHidden();

    await page.getByRole('button', { name: /reveal solution/i }).click();
    await expect(article.getByText(/cyclic of order f, generated by T/i)).toBeVisible();

    expect(await page.evaluate((k) => window.localStorage.getItem(k), PROOF_KEY)).toContain(
      '"outcome":"revealed"',
    );

    await page.reload();
    await expect(article.getByText(/cyclic of order f, generated by T/i)).toBeVisible();
  });
});

// ── Problem flow ──────────────────────────────────────────────────────────────
test.describe('Frobenius element — Problem flow ((2/p) via quadratic reciprocity)', () => {
  const SLIDE = `${BASE}/09-problems/01-intro-and-standard`;
  const PROB_KEY = `napkin:exercise:${SLIDE}#frob-prob-two-over-p`;

  test('showing solution writes to localStorage', async ({ page }) => {
    await page.goto(SLIDE);

    const article = page.getByRole('article');
    // This phrase only appears inside the solution, not the prompt or hint.
    await expect(article.getByText(/checking all four odd residues mod 8/i)).toBeHidden();

    await page.getByRole('button', { name: /show solution/i }).first().click();
    await expect(article.getByText(/checking all four odd residues mod 8/i)).toBeVisible();

    const stored = await page.evaluate((k) => window.localStorage.getItem(k), PROB_KEY);
    expect(stored).not.toBeNull();
  });
});
